services:
  api:
    image: ${REGISTRY:-saizhuolin}/example-file-api:${VERSION:-latest}
    build: 
      context: ./api
    container_name: example-file-api
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-server -Xms2048m -Xmx2048m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -Dbella.proxy.host=${PROXY_HOST:-} -Dbella.proxy.port=${PROXY_PORT:-} -Dbella.proxy.type=${PROXY_TYPE:-} -Dbella.storage.config=${STORAGE_CONFIG:-}
      - SPRING_PROFILES_ACTIVE=docker
      - BELLA_OPEN_API_BASE=${OPENAPI_URL:-https://localhost:8080/}
      - BELLA_STORAGE_TYPE=${STORAGE_TYPE:-local}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=bella_user
      - MYSQL_PASSWORD=123456
    volumes:
      - ./api/applogs:/opt/example-file-api/applogs
      - ./api/logs:/opt/example-file-api/logs
      - ./api/cache:/opt/example-file-api/cache
      - ./api/config-cache:/opt/example-file-api/config-cache
    depends_on:
      mysql:
        condition: service_healthy
      
  mysql:
    image: mysql:8.0
    container_name: example-file-api-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bella_file_api
      MYSQL_USER: bella_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./api/sql:/docker-entrypoint-initdb.d
    privileged: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "bella_user", "--password=123456"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:latest
    container_name: example-file-api-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api