/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db;


import com.ke.bella.files.db.tables.Dataset;
import com.ke.bella.files.db.tables.DatasetDocument;
import com.ke.bella.files.db.tables.DatasetQa;
import com.ke.bella.files.db.tables.DatasetQaReference;
import com.ke.bella.files.db.tables.DatasetSharding;
import com.ke.bella.files.db.tables.File;
import com.ke.bella.files.db.tables.FileMapping;
import com.ke.bella.files.db.tables.FileProgress;
import com.ke.bella.files.db.tables.Instance;
import com.ke.bella.files.db.tables.Tag;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * 数据集
     */
    public final Dataset DATASET = Dataset.DATASET;

    /**
     * 文档数据集表
     */
    public final DatasetDocument DATASET_DOCUMENT = DatasetDocument.DATASET_DOCUMENT;

    /**
     * 问答数据集表
     */
    public final DatasetQa DATASET_QA = DatasetQa.DATASET_QA;

    /**
     * 数据集问答对引用关系表
     */
    public final DatasetQaReference DATASET_QA_REFERENCE = DatasetQaReference.DATASET_QA_REFERENCE;

    /**
     * The table <code>dataset_sharding</code>.
     */
    public final DatasetSharding DATASET_SHARDING = DatasetSharding.DATASET_SHARDING;

    /**
     * The table <code>file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>file_mapping</code>.
     */
    public final FileMapping FILE_MAPPING = FileMapping.FILE_MAPPING;

    /**
     * The table <code>file_progress</code>.
     */
    public final FileProgress FILE_PROGRESS = FileProgress.FILE_PROGRESS;

    /**
     * The table <code>instance</code>.
     */
    public final Instance INSTANCE = Instance.INSTANCE;

    /**
     * 标签定义表
     */
    public final Tag TAG = Tag.TAG;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Dataset.DATASET,
            DatasetDocument.DATASET_DOCUMENT,
            DatasetQa.DATASET_QA,
            DatasetQaReference.DATASET_QA_REFERENCE,
            DatasetSharding.DATASET_SHARDING,
            File.FILE,
            FileMapping.FILE_MAPPING,
            FileProgress.FILE_PROGRESS,
            Instance.INSTANCE,
            Tag.TAG);
    }
}
