/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db;


import com.ke.bella.files.db.tables.File;
import com.ke.bella.files.db.tables.FileMapping;
import com.ke.bella.files.db.tables.FileProgress;
import com.ke.bella.files.db.tables.Instance;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>file_mapping</code>.
     */
    public final FileMapping FILE_MAPPING = FileMapping.FILE_MAPPING;

    /**
     * The table <code>file_progress</code>.
     */
    public final FileProgress FILE_PROGRESS = FileProgress.FILE_PROGRESS;

    /**
     * The table <code>instance</code>.
     */
    public final Instance INSTANCE = Instance.INSTANCE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            File.FILE,
            FileMapping.FILE_MAPPING,
            FileProgress.FILE_PROGRESS,
            Instance.INSTANCE);
    }
}
