/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db;


import com.ke.bella.files.db.tables.Dataset;
import com.ke.bella.files.db.tables.DatasetDocument;
import com.ke.bella.files.db.tables.DatasetQa;
import com.ke.bella.files.db.tables.DatasetQaReference;
import com.ke.bella.files.db.tables.DatasetSharding;
import com.ke.bella.files.db.tables.File;
import com.ke.bella.files.db.tables.FileClosure;
import com.ke.bella.files.db.tables.Instance;
import com.ke.bella.files.db.tables.Tag;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FILE_CLOSURE_IDX_ANCESTOR_DEPTH_STATUS = Internal.createIndex(DSL.name("idx_ancestor_depth_status"), FileClosure.FILE_CLOSURE, new OrderField[] { FileClosure.FILE_CLOSURE.ANCESTOR_ID, FileClosure.FILE_CLOSURE.DEPTH }, false);
    public static final Index DATASET_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), Dataset.DATASET, new OrderField[] { Dataset.DATASET.CTIME }, false);
    public static final Index DATASET_DOCUMENT_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), DatasetDocument.DATASET_DOCUMENT, new OrderField[] { DatasetDocument.DATASET_DOCUMENT.CTIME }, false);
    public static final Index DATASET_QA_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), DatasetQa.DATASET_QA, new OrderField[] { DatasetQa.DATASET_QA.CTIME }, false);
    public static final Index DATASET_QA_REFERENCE_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), DatasetQaReference.DATASET_QA_REFERENCE, new OrderField[] { DatasetQaReference.DATASET_QA_REFERENCE.CTIME }, false);
    public static final Index FILE_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), File.FILE, new OrderField[] { File.FILE.CTIME }, false);
    public static final Index TAG_IDX_CTIME = Internal.createIndex(DSL.name("idx_ctime"), Tag.TAG, new OrderField[] { Tag.TAG.CTIME }, false);
    public static final Index DATASET_DOCUMENT_IDX_DATASET_ID = Internal.createIndex(DSL.name("idx_dataset_id"), DatasetDocument.DATASET_DOCUMENT, new OrderField[] { DatasetDocument.DATASET_DOCUMENT.DATASET_ID }, false);
    public static final Index DATASET_QA_REFERENCE_IDX_DATASET_ID = Internal.createIndex(DSL.name("idx_dataset_id"), DatasetQaReference.DATASET_QA_REFERENCE, new OrderField[] { DatasetQaReference.DATASET_QA_REFERENCE.DATASET_ID }, false);
    public static final Index DATASET_QA_IDX_DATASET_ITEM = Internal.createIndex(DSL.name("idx_dataset_item"), DatasetQa.DATASET_QA, new OrderField[] { DatasetQa.DATASET_QA.DATASET_ID, DatasetQa.DATASET_QA.ITEM_ID }, false);
    public static final Index FILE_CLOSURE_IDX_DESCENDANT_DEPTH_STATUS = Internal.createIndex(DSL.name("idx_descendant_depth_status"), FileClosure.FILE_CLOSURE, new OrderField[] { FileClosure.FILE_CLOSURE.DESCENDANT_ID, FileClosure.FILE_CLOSURE.DEPTH }, false);
    public static final Index DATASET_DOCUMENT_IDX_FILE_ID = Internal.createIndex(DSL.name("idx_file_id"), DatasetDocument.DATASET_DOCUMENT, new OrderField[] { DatasetDocument.DATASET_DOCUMENT.FILE_ID }, false);
    public static final Index FILE_IDX_FILENAME_STATUS = Internal.createIndex(DSL.name("idx_filename_status"), File.FILE, new OrderField[] { File.FILE.FILENAME, File.FILE.STATUS }, false);
    public static final Index INSTANCE_IDX_IP_PORT = Internal.createIndex(DSL.name("idx_ip_port"), Instance.INSTANCE, new OrderField[] { Instance.INSTANCE.IP, Instance.INSTANCE.PORT }, false);
    public static final Index DATASET_QA_REFERENCE_IDX_ITEM_ID = Internal.createIndex(DSL.name("idx_item_id"), DatasetQaReference.DATASET_QA_REFERENCE, new OrderField[] { DatasetQaReference.DATASET_QA_REFERENCE.ITEM_ID }, false);
    public static final Index DATASET_IDX_MTIME = Internal.createIndex(DSL.name("idx_mtime"), Dataset.DATASET, new OrderField[] { Dataset.DATASET.MTIME }, false);
    public static final Index DATASET_QA_IDX_MTIME = Internal.createIndex(DSL.name("idx_mtime"), DatasetQa.DATASET_QA, new OrderField[] { DatasetQa.DATASET_QA.MTIME }, false);
    public static final Index DATASET_QA_REFERENCE_IDX_MTIME = Internal.createIndex(DSL.name("idx_mtime"), DatasetQaReference.DATASET_QA_REFERENCE, new OrderField[] { DatasetQaReference.DATASET_QA_REFERENCE.MTIME }, false);
    public static final Index DATASET_IDX_SPACE_CODE = Internal.createIndex(DSL.name("idx_space_code"), Dataset.DATASET, new OrderField[] { Dataset.DATASET.SPACE_CODE }, false);
    public static final Index FILE_CLOSURE_IDX_SPACE_CODE_ROOT_DEPTH = Internal.createIndex(DSL.name("idx_space_code_root_depth"), FileClosure.FILE_CLOSURE, new OrderField[] { FileClosure.FILE_CLOSURE.SPACE_CODE, FileClosure.FILE_CLOSURE.ROOT_DEPTH }, false);
    public static final Index FILE_IDX_SPACE_PURPOSE = Internal.createIndex(DSL.name("idx_space_purpose"), File.FILE, new OrderField[] { File.FILE.SPACE_CODE, File.FILE.PURPOSE, File.FILE.STATUS }, false);
    public static final Index DATASET_SHARDING_IDX_TYPE_LAST_KEY = Internal.createIndex(DSL.name("idx_type_last_key"), DatasetSharding.DATASET_SHARDING, new OrderField[] { DatasetSharding.DATASET_SHARDING.TYPE, DatasetSharding.DATASET_SHARDING.LAST_KEY }, false);
}
