/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db;


import com.ke.bella.files.db.tables.Dataset;
import com.ke.bella.files.db.tables.DatasetDocument;
import com.ke.bella.files.db.tables.DatasetQa;
import com.ke.bella.files.db.tables.DatasetQaReference;
import com.ke.bella.files.db.tables.DatasetSharding;
import com.ke.bella.files.db.tables.File;
import com.ke.bella.files.db.tables.FileClosure;
import com.ke.bella.files.db.tables.FileMapping;
import com.ke.bella.files.db.tables.FileProgress;
import com.ke.bella.files.db.tables.FileProgressTemp;
import com.ke.bella.files.db.tables.FileSharding;
import com.ke.bella.files.db.tables.FileSystem;
import com.ke.bella.files.db.tables.FileTemp;
import com.ke.bella.files.db.tables.Instance;
import com.ke.bella.files.db.tables.Tag;
import com.ke.bella.files.db.tables.records.DatasetDocumentRecord;
import com.ke.bella.files.db.tables.records.DatasetQaRecord;
import com.ke.bella.files.db.tables.records.DatasetQaReferenceRecord;
import com.ke.bella.files.db.tables.records.DatasetRecord;
import com.ke.bella.files.db.tables.records.DatasetShardingRecord;
import com.ke.bella.files.db.tables.records.FileClosureRecord;
import com.ke.bella.files.db.tables.records.FileMappingRecord;
import com.ke.bella.files.db.tables.records.FileProgressRecord;
import com.ke.bella.files.db.tables.records.FileProgressTempRecord;
import com.ke.bella.files.db.tables.records.FileRecord;
import com.ke.bella.files.db.tables.records.FileShardingRecord;
import com.ke.bella.files.db.tables.records.FileSystemRecord;
import com.ke.bella.files.db.tables.records.FileTempRecord;
import com.ke.bella.files.db.tables.records.InstanceRecord;
import com.ke.bella.files.db.tables.records.TagRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatasetRecord> KEY_DATASET_IDX_DATASET_ID = Internal.createUniqueKey(Dataset.DATASET, DSL.name("KEY_dataset_idx_dataset_id"), new TableField[] { Dataset.DATASET.DATASET_ID }, true);
    public static final UniqueKey<DatasetRecord> KEY_DATASET_PRIMARY = Internal.createUniqueKey(Dataset.DATASET, DSL.name("KEY_dataset_PRIMARY"), new TableField[] { Dataset.DATASET.ID }, true);
    public static final UniqueKey<DatasetDocumentRecord> KEY_DATASET_DOCUMENT_IDX_DATASET_FILE = Internal.createUniqueKey(DatasetDocument.DATASET_DOCUMENT, DSL.name("KEY_dataset_document_idx_dataset_file"), new TableField[] { DatasetDocument.DATASET_DOCUMENT.DATASET_ID, DatasetDocument.DATASET_DOCUMENT.FILE_ID }, true);
    public static final UniqueKey<DatasetDocumentRecord> KEY_DATASET_DOCUMENT_PRIMARY = Internal.createUniqueKey(DatasetDocument.DATASET_DOCUMENT, DSL.name("KEY_dataset_document_PRIMARY"), new TableField[] { DatasetDocument.DATASET_DOCUMENT.ID }, true);
    public static final UniqueKey<DatasetQaRecord> KEY_DATASET_QA_IDX_ITEM_ID = Internal.createUniqueKey(DatasetQa.DATASET_QA, DSL.name("KEY_dataset_qa_idx_item_id"), new TableField[] { DatasetQa.DATASET_QA.ITEM_ID }, true);
    public static final UniqueKey<DatasetQaRecord> KEY_DATASET_QA_PRIMARY = Internal.createUniqueKey(DatasetQa.DATASET_QA, DSL.name("KEY_dataset_qa_PRIMARY"), new TableField[] { DatasetQa.DATASET_QA.ID }, true);
    public static final UniqueKey<DatasetQaReferenceRecord> KEY_DATASET_QA_REFERENCE_IDX_REFERENCE_ID = Internal.createUniqueKey(DatasetQaReference.DATASET_QA_REFERENCE, DSL.name("KEY_dataset_qa_reference_idx_reference_id"), new TableField[] { DatasetQaReference.DATASET_QA_REFERENCE.REFERENCE_ID }, true);
    public static final UniqueKey<DatasetQaReferenceRecord> KEY_DATASET_QA_REFERENCE_PRIMARY = Internal.createUniqueKey(DatasetQaReference.DATASET_QA_REFERENCE, DSL.name("KEY_dataset_qa_reference_PRIMARY"), new TableField[] { DatasetQaReference.DATASET_QA_REFERENCE.ID }, true);
    public static final UniqueKey<DatasetShardingRecord> KEY_DATASET_SHARDING_IDX_TYPE_KEY = Internal.createUniqueKey(DatasetSharding.DATASET_SHARDING, DSL.name("KEY_dataset_sharding_idx_type_key"), new TableField[] { DatasetSharding.DATASET_SHARDING.TYPE, DatasetSharding.DATASET_SHARDING.KEY }, true);
    public static final UniqueKey<DatasetShardingRecord> KEY_DATASET_SHARDING_PRIMARY = Internal.createUniqueKey(DatasetSharding.DATASET_SHARDING, DSL.name("KEY_dataset_sharding_PRIMARY"), new TableField[] { DatasetSharding.DATASET_SHARDING.ID }, true);
    public static final UniqueKey<FileRecord> KEY_FILE_IDX_FILE_SPACE = Internal.createUniqueKey(File.FILE, DSL.name("KEY_file_idx_file_space"), new TableField[] { File.FILE.FILE_ID, File.FILE.SPACE_CODE }, true);
    public static final UniqueKey<FileRecord> KEY_FILE_PRIMARY = Internal.createUniqueKey(File.FILE, DSL.name("KEY_file_PRIMARY"), new TableField[] { File.FILE.ID }, true);
    public static final UniqueKey<FileClosureRecord> KEY_FILE_CLOSURE_IDX_ANCESTOR_DESCENDANT = Internal.createUniqueKey(FileClosure.FILE_CLOSURE, DSL.name("KEY_file_closure_idx_ancestor_descendant"), new TableField[] { FileClosure.FILE_CLOSURE.ANCESTOR_ID, FileClosure.FILE_CLOSURE.DESCENDANT_ID }, true);
    public static final UniqueKey<FileClosureRecord> KEY_FILE_CLOSURE_PRIMARY = Internal.createUniqueKey(FileClosure.FILE_CLOSURE, DSL.name("KEY_file_closure_PRIMARY"), new TableField[] { FileClosure.FILE_CLOSURE.ID }, true);
    public static final UniqueKey<FileMappingRecord> KEY_FILE_MAPPING_IDX_FILE_ID_NEW_OLD = Internal.createUniqueKey(FileMapping.FILE_MAPPING, DSL.name("KEY_file_mapping_idx_file_id_new_old"), new TableField[] { FileMapping.FILE_MAPPING.FILE_ID_OLD, FileMapping.FILE_MAPPING.FILE_ID }, true);
    public static final UniqueKey<FileMappingRecord> KEY_FILE_MAPPING_PRIMARY = Internal.createUniqueKey(FileMapping.FILE_MAPPING, DSL.name("KEY_file_mapping_PRIMARY"), new TableField[] { FileMapping.FILE_MAPPING.ID }, true);
    public static final UniqueKey<FileProgressRecord> KEY_FILE_PROGRESS_IDX_FILE_ID_NAME = Internal.createUniqueKey(FileProgress.FILE_PROGRESS, DSL.name("KEY_file_progress_idx_file_id_name"), new TableField[] { FileProgress.FILE_PROGRESS.FILE_ID, FileProgress.FILE_PROGRESS.NAME }, true);
    public static final UniqueKey<FileProgressRecord> KEY_FILE_PROGRESS_PRIMARY = Internal.createUniqueKey(FileProgress.FILE_PROGRESS, DSL.name("KEY_file_progress_PRIMARY"), new TableField[] { FileProgress.FILE_PROGRESS.ID }, true);
    public static final UniqueKey<FileProgressTempRecord> KEY_FILE_PROGRESS_TEMP_IDX_FILE_ID_NAME = Internal.createUniqueKey(FileProgressTemp.FILE_PROGRESS_TEMP, DSL.name("KEY_file_progress_temp_idx_file_id_name"), new TableField[] { FileProgressTemp.FILE_PROGRESS_TEMP.FILE_ID, FileProgressTemp.FILE_PROGRESS_TEMP.NAME }, true);
    public static final UniqueKey<FileProgressTempRecord> KEY_FILE_PROGRESS_TEMP_PRIMARY = Internal.createUniqueKey(FileProgressTemp.FILE_PROGRESS_TEMP, DSL.name("KEY_file_progress_temp_PRIMARY"), new TableField[] { FileProgressTemp.FILE_PROGRESS_TEMP.ID }, true);
    public static final UniqueKey<FileShardingRecord> KEY_FILE_SHARDING_IDX_TYPE_KEY = Internal.createUniqueKey(FileSharding.FILE_SHARDING, DSL.name("KEY_file_sharding_idx_type_key"), new TableField[] { FileSharding.FILE_SHARDING.TYPE, FileSharding.FILE_SHARDING.KEY }, true);
    public static final UniqueKey<FileShardingRecord> KEY_FILE_SHARDING_PRIMARY = Internal.createUniqueKey(FileSharding.FILE_SHARDING, DSL.name("KEY_file_sharding_PRIMARY"), new TableField[] { FileSharding.FILE_SHARDING.ID }, true);
    public static final UniqueKey<FileSystemRecord> KEY_FILE_SYSTEM_IDX_FILE_SPACE = Internal.createUniqueKey(FileSystem.FILE_SYSTEM, DSL.name("KEY_file_system_idx_file_space"), new TableField[] { FileSystem.FILE_SYSTEM.FILE_ID, FileSystem.FILE_SYSTEM.SPACE_CODE }, true);
    public static final UniqueKey<FileSystemRecord> KEY_FILE_SYSTEM_PRIMARY = Internal.createUniqueKey(FileSystem.FILE_SYSTEM, DSL.name("KEY_file_system_PRIMARY"), new TableField[] { FileSystem.FILE_SYSTEM.ID }, true);
    public static final UniqueKey<FileTempRecord> KEY_FILE_TEMP_IDX_FILE_SPACE = Internal.createUniqueKey(FileTemp.FILE_TEMP, DSL.name("KEY_file_temp_idx_file_space"), new TableField[] { FileTemp.FILE_TEMP.FILE_ID, FileTemp.FILE_TEMP.SPACE_CODE }, true);
    public static final UniqueKey<FileTempRecord> KEY_FILE_TEMP_PRIMARY = Internal.createUniqueKey(FileTemp.FILE_TEMP, DSL.name("KEY_file_temp_PRIMARY"), new TableField[] { FileTemp.FILE_TEMP.ID }, true);
    public static final UniqueKey<InstanceRecord> KEY_INSTANCE_PRIMARY = Internal.createUniqueKey(Instance.INSTANCE, DSL.name("KEY_instance_PRIMARY"), new TableField[] { Instance.INSTANCE.ID }, true);
    public static final UniqueKey<TagRecord> KEY_TAG_IDX_SPACE_NAME = Internal.createUniqueKey(Tag.TAG, DSL.name("KEY_tag_idx_space_name"), new TableField[] { Tag.TAG.SPACE_CODE, Tag.TAG.NAME }, true);
    public static final UniqueKey<TagRecord> KEY_TAG_PRIMARY = Internal.createUniqueKey(Tag.TAG, DSL.name("KEY_tag_PRIMARY"), new TableField[] { Tag.TAG.ID }, true);
}
