/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db;


import com.ke.bella.files.db.tables.File;
import com.ke.bella.files.db.tables.FileMapping;
import com.ke.bella.files.db.tables.FileProgress;
import com.ke.bella.files.db.tables.Instance;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>file</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>file_mapping</code>.
     */
    public static final FileMapping FILE_MAPPING = FileMapping.FILE_MAPPING;

    /**
     * The table <code>file_progress</code>.
     */
    public static final FileProgress FILE_PROGRESS = FileProgress.FILE_PROGRESS;

    /**
     * The table <code>instance</code>.
     */
    public static final Instance INSTANCE = Instance.INSTANCE;
}
