/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db;


import com.ke.bella.files.db.tables.Dataset;
import com.ke.bella.files.db.tables.DatasetDocument;
import com.ke.bella.files.db.tables.DatasetQa;
import com.ke.bella.files.db.tables.DatasetQaReference;
import com.ke.bella.files.db.tables.DatasetSharding;
import com.ke.bella.files.db.tables.File;
import com.ke.bella.files.db.tables.FileMapping;
import com.ke.bella.files.db.tables.FileProgress;
import com.ke.bella.files.db.tables.Instance;
import com.ke.bella.files.db.tables.Tag;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 数据集
     */
    public static final Dataset DATASET = Dataset.DATASET;

    /**
     * 文档数据集表
     */
    public static final DatasetDocument DATASET_DOCUMENT = DatasetDocument.DATASET_DOCUMENT;

    /**
     * 问答数据集表
     */
    public static final DatasetQa DATASET_QA = DatasetQa.DATASET_QA;

    /**
     * 数据集问答对引用关系表
     */
    public static final DatasetQaReference DATASET_QA_REFERENCE = DatasetQaReference.DATASET_QA_REFERENCE;

    /**
     * The table <code>dataset_sharding</code>.
     */
    public static final DatasetSharding DATASET_SHARDING = DatasetSharding.DATASET_SHARDING;

    /**
     * The table <code>file</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>file_mapping</code>.
     */
    public static final FileMapping FILE_MAPPING = FileMapping.FILE_MAPPING;

    /**
     * The table <code>file_progress</code>.
     */
    public static final FileProgress FILE_PROGRESS = FileProgress.FILE_PROGRESS;

    /**
     * The table <code>instance</code>.
     */
    public static final Instance INSTANCE = Instance.INSTANCE;

    /**
     * 标签定义表
     */
    public static final Tag TAG = Tag.TAG;
}
