spring:
  application:
    name: example-file-api
  datasource:
    url: jdbc:mysql://localhost:3306/bella_file_api?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:bella123}
app:
  id: example-file-api

bella:
  open-api-base: https://localhost:8080/
  file-api:
    file:
      tmp-file-dir: .
    bucket-name:
      public: test
      private: test
    storage:
      type: local
  server:
    initializer:
      enabled: true
  task:
    thread-nums: 1000
  login:
    type: client
    openapi-base: ${BELLA_LOGIN_OPENAPI_BASE:http://localhost}
  session:
    cookie-name: ${BELLA_COOKIE_NAME:bella_openapi_sessionId}
    max-inactive-interval: 60
    cookie-max-age: -1
    cookie-domain: ${BELLA_COOKIE_DOMAIN:localhost}
    cookie-context-path: /
  datasets:
    import:
      batch-size: 500
apollo:
  bootstrap:
    enabled: false
    eagerLoad:
      enabled: true
    namespaces: application
  property:
    order:
      enabled: true
  cacheDir: ./config-cache
  cluster: default
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  health:
    redis:
      enabled: false
server:
  port: 8081

# ----- 日志级别配置 测试环境 -----
logging:
  level:
    root: INFO
    druid: INFO
    executableSql: INFO
    org:
      springframework: INFO
      jooq: DEBUG
