spring:
  application:
    name: bella-file-api
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:bella_file_api}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:bella123}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:common-queue-04-01-online.zeus.ljnode.com:9092,common-queue-04-02-online.zeus.ljnode.com:9092,common-queue-04-03-online.zeus.ljnode.com:9092}
      value-serializer: ${KAFKA_PRODUCER_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}
      key-serializer: ${KAFKA_PRODUCER_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      topic:
        broadcast: ${KAFKA_TOPIC_BROADCAST:bella_file_api}
app:
  id: bella-file-api

bella:
  open-api-base: ${BELLA_OPEN_API_BASE:https://localhost:8080/}
  file-api:
    file:
      tmp-file-dir: ${BELLA_TMP_FILE_DIR:.}
      exists:
        block: false
    bucket-name:
      public: ${BELLA_STORAGE_S3_BUCKET:test}
      private: ${BELLA_STORAGE_S3_BUCKET:test}
    storage:
      type: ${BELLA_STORAGE_TYPE:local}
  server:
    initializer:
      enabled: true
  task:
    thread-nums: 1000
  login:
    type: ${BELLA_LOGIN_TYPE:client}
    openapi-base: ${BELLA_OPENAPI_URL:http://localhost}
    authorization-header: Authorization
  session:
    cookie-name: ${BELLA_COOKIE_NAME:bella_openapi_sessionId}
    max-inactive-interval: 60
    cookie-max-age: -1
    cookie-domain: ${BELLA_SESSION_COOKIE_DOMAIN:ke.com}
    cookie-context-path: /
  datasets:
    import:
      batch-size: 500
apollo:
  bootstrap:
    enabled: false
    eagerLoad:
      enabled: true
    namespaces: application
  property:
    order:
      enabled: true
  cacheDir: ./config-cache
  cluster: default
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  health:
    redis:
      enabled: false
server:
  port: 8081

# ----- 日志级别配置 测试环境 -----
logging:
  level:
    root: INFO
    druid: INFO
    executableSql: INFO
    org:
      springframework: INFO
      jooq: DEBUG
