#-------------------------------------------------------
# PROD环境配置区域
#-------------------------------------------------------
apollo:
  meta: http://example.com
# ----- 日志级别配置 生产环境 -----
logging:
  level:
    root: INFO
    druid: INFO
    executableSql: INFO
    org:
      springframework: INFO
      jooq: INFO

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_POOL_MASTER_URL}
    username: ${DATASOURCE_POOL_MASTER_USERNAME}
    password: ${DATASOURCE_POOL_MASTER_PASSWORD}
    hikari:
      minimum-idle: 50
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: BellaHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
  kafka:
    producer:
      bootstrap-servers: common-queue-04-01-online.zeus.ljnode.com:9092,common-queue-04-02-online.zeus.ljnode.com:9092,common-queue-04-03-online.zeus.ljnode.com:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic:
        broadcast: bella-file-broadcast

bella:
  open-api-base: https://api.example.com/
  file-api:
    processer-name:
      - indexing
      - parser
    file:
      tmp-file-dir: /data0/www/privdata/example-file-api
    bucket-name:
      vision: bella-file-public
      general: bella-file-private
s3:
  ak: 57856TV6QN2MEEQL27AL
  sk: 6e0SprFtGzl4jFSOFta9KxTgeXPn62pOeqg7TnAq
  endpoint_write: https://example.com
  endpoint_read_private: https://example.com
  endpoint_read_public: https://file.ljcdn.com
  endpoint_preview: https://example.com
  ak_preview: BBNQW9PF2N9IYI8MUEEC
  sk_preview: dl4MXzlqCFEmf0KBHn/l2eK5nipqkIbehI7eo5hI
server:
  tomcat:
    max-swallow-size: -1
