#-------------------------------------------------------
# TEST环境配置区域
#-------------------------------------------------------
apollo:
  bootstrap:
    enabled: true
  meta: http://config.example.com
# ----- 日志级别配置 测试环境 -----
logging:
  level:
    root: INFO
    druid: INFO
    executableSql: INFO
    org:
      springframework: INFO
      jooq: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_POOL_MASTER_URL}
    username: ${DATASOURCE_POOL_MASTER_USERNAME}
    password: ${DATASOURCE_POOL_MASTER_PASSWORD}
    hikari:
      minimum-idle: 50
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: BellaHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
  kafka:
    producer:
      bootstrap-servers: kafka1.example.com:9092,kafka2.example.com:9092,kafka3.example.com:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic:
        broadcast: example-topic
  redis:
    host: redis.example.com
    port: 10373
    password: redis_password

bella:
  open-api-base: https://api.example.com/
  file-api:
    file:
      tmp-file-dir: /data0/www/privdata/example-file-api
    bucket-name:
      public: test
      private: test
    storage:
      type: ke
      ke:
        ak: access_key
        sk: secret_key
        endpoint: http://storage.example.com
        endpoint_read_private: http://storage.example.com
        endpoint_read_public: http://storage.example.com
        endpoint_preview: http://preview.example.com
        ak_preview: access_key
        sk_preview: secret_key
        region: cn-north-1
server:
  tomcat:
    max-swallow-size: -1
  port: 8080
