/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.DatasetShardingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetSharding extends TableImpl<DatasetShardingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>dataset_sharding</code>
     */
    public static final DatasetSharding DATASET_SHARDING = new DatasetSharding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatasetShardingRecord> getRecordType() {
        return DatasetShardingRecord.class;
    }

    /**
     * The column <code>dataset_sharding.id</code>.
     */
    public final TableField<DatasetShardingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>dataset_sharding.type</code>. 分片类型：qa-问答数据，document-文档数据
     */
    public final TableField<DatasetShardingRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("qa", SQLDataType.VARCHAR)), this, "分片类型：qa-问答数据，document-文档数据");

    /**
     * The column <code>dataset_sharding.key</code>. 分表的标识，
对应的表+’_’+key即是实际读写的表
     */
    public final TableField<DatasetShardingRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "分表的标识，\n对应的表+’_’+key即是实际读写的表");

    /**
     * The column <code>dataset_sharding.key_time</code>. 当前分片第一条数据的时间，用于索引分片
     */
    public final TableField<DatasetShardingRecord, LocalDateTime> KEY_TIME = createField(DSL.name("key_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "当前分片第一条数据的时间，用于索引分片");

    /**
     * The column <code>dataset_sharding.last_key</code>. 上一次分表的标识，用于分表创建并发控制
     */
    public final TableField<DatasetShardingRecord, String> LAST_KEY = createField(DSL.name("last_key"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "上一次分表的标识，用于分表创建并发控制");

    /**
     * The column <code>dataset_sharding.count</code>. 分表的记录数量
     */
    public final TableField<DatasetShardingRecord, Long> COUNT = createField(DSL.name("count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "分表的记录数量");

    /**
     * The column <code>dataset_sharding.max_count</code>. 分表的最大记录数
如果count&gt;max_count， 创建新表
     */
    public final TableField<DatasetShardingRecord, Long> MAX_COUNT = createField(DSL.name("max_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("20000000", SQLDataType.BIGINT)), this, "分表的最大记录数\n如果count>max_count， 创建新表");

    /**
     * The column <code>dataset_sharding.ctime</code>.
     */
    public final TableField<DatasetShardingRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dataset_sharding.cu_name</code>.
     */
    public final TableField<DatasetShardingRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dataset_sharding.cuid</code>.
     */
    public final TableField<DatasetShardingRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dataset_sharding.mtime</code>.
     */
    public final TableField<DatasetShardingRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dataset_sharding.mu_name</code>.
     */
    public final TableField<DatasetShardingRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dataset_sharding.muid</code>.
     */
    public final TableField<DatasetShardingRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    private DatasetSharding(Name alias, Table<DatasetShardingRecord> aliased) {
        this(alias, aliased, null);
    }

    private DatasetSharding(Name alias, Table<DatasetShardingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>dataset_sharding</code> table reference
     */
    public DatasetSharding(String alias) {
        this(DSL.name(alias), DATASET_SHARDING);
    }

    /**
     * Create an aliased <code>dataset_sharding</code> table reference
     */
    public DatasetSharding(Name alias) {
        this(alias, DATASET_SHARDING);
    }

    /**
     * Create a <code>dataset_sharding</code> table reference
     */
    public DatasetSharding() {
        this(DSL.name("dataset_sharding"), null);
    }

    public <O extends Record> DatasetSharding(Table<O> child, ForeignKey<O, DatasetShardingRecord> key) {
        super(child, key, DATASET_SHARDING);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATASET_SHARDING_IDX_TYPE_LAST_KEY);
    }

    @Override
    public Identity<DatasetShardingRecord, Long> getIdentity() {
        return (Identity<DatasetShardingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DatasetShardingRecord> getPrimaryKey() {
        return Keys.KEY_DATASET_SHARDING_PRIMARY;
    }

    @Override
    public List<UniqueKey<DatasetShardingRecord>> getKeys() {
        return Arrays.<UniqueKey<DatasetShardingRecord>>asList(Keys.KEY_DATASET_SHARDING_PRIMARY, Keys.KEY_DATASET_SHARDING_IDX_TYPE_KEY);
    }

    @Override
    public DatasetSharding as(String alias) {
        return new DatasetSharding(DSL.name(alias), this);
    }

    @Override
    public DatasetSharding as(Name alias) {
        return new DatasetSharding(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetSharding rename(String name) {
        return new DatasetSharding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetSharding rename(Name name) {
        return new DatasetSharding(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, LocalDateTime, String, Long, Long, LocalDateTime, String, Long, LocalDateTime, String, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
