/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.DatasetDocumentRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 文档数据集表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetDocument extends TableImpl<DatasetDocumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>dataset_document</code>
     */
    public static final DatasetDocument DATASET_DOCUMENT = new DatasetDocument();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatasetDocumentRecord> getRecordType() {
        return DatasetDocumentRecord.class;
    }

    /**
     * The column <code>dataset_document.id</code>.
     */
    public final TableField<DatasetDocumentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>dataset_document.dataset_sharding_key</code>. 数据集分片的key
     */
    public final TableField<DatasetDocumentRecord, String> DATASET_SHARDING_KEY = createField(DSL.name("dataset_sharding_key"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "数据集分片的key");

    /**
     * The column <code>dataset_document.dataset_id</code>. 数据集ID
     */
    public final TableField<DatasetDocumentRecord, String> DATASET_ID = createField(DSL.name("dataset_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "数据集ID");

    /**
     * The column <code>dataset_document.file_id</code>. 文件ID，作为document的主键
     */
    public final TableField<DatasetDocumentRecord, String> FILE_ID = createField(DSL.name("file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件ID，作为document的主键");

    /**
     * The column <code>dataset_document.cuid</code>.
     */
    public final TableField<DatasetDocumentRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dataset_document.cu_name</code>.
     */
    public final TableField<DatasetDocumentRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dataset_document.ctime</code>.
     */
    public final TableField<DatasetDocumentRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dataset_document.muid</code>.
     */
    public final TableField<DatasetDocumentRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dataset_document.mu_name</code>.
     */
    public final TableField<DatasetDocumentRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dataset_document.mtime</code>.
     */
    public final TableField<DatasetDocumentRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dataset_document.status</code>. 文档是否被删除，0表示未删除，-1表示已删除
     */
    public final TableField<DatasetDocumentRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "文档是否被删除，0表示未删除，-1表示已删除");

    private DatasetDocument(Name alias, Table<DatasetDocumentRecord> aliased) {
        this(alias, aliased, null);
    }

    private DatasetDocument(Name alias, Table<DatasetDocumentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("文档数据集表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>dataset_document</code> table reference
     */
    public DatasetDocument(String alias) {
        this(DSL.name(alias), DATASET_DOCUMENT);
    }

    /**
     * Create an aliased <code>dataset_document</code> table reference
     */
    public DatasetDocument(Name alias) {
        this(alias, DATASET_DOCUMENT);
    }

    /**
     * Create a <code>dataset_document</code> table reference
     */
    public DatasetDocument() {
        this(DSL.name("dataset_document"), null);
    }

    public <O extends Record> DatasetDocument(Table<O> child, ForeignKey<O, DatasetDocumentRecord> key) {
        super(child, key, DATASET_DOCUMENT);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATASET_DOCUMENT_IDX_CTIME, Indexes.DATASET_DOCUMENT_IDX_DATASET_ID, Indexes.DATASET_DOCUMENT_IDX_FILE_ID);
    }

    @Override
    public Identity<DatasetDocumentRecord, Long> getIdentity() {
        return (Identity<DatasetDocumentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DatasetDocumentRecord> getPrimaryKey() {
        return Keys.KEY_DATASET_DOCUMENT_PRIMARY;
    }

    @Override
    public List<UniqueKey<DatasetDocumentRecord>> getKeys() {
        return Arrays.<UniqueKey<DatasetDocumentRecord>>asList(Keys.KEY_DATASET_DOCUMENT_PRIMARY, Keys.KEY_DATASET_DOCUMENT_IDX_DATASET_FILE);
    }

    @Override
    public DatasetDocument as(String alias) {
        return new DatasetDocument(DSL.name(alias), this);
    }

    @Override
    public DatasetDocument as(Name alias) {
        return new DatasetDocument(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetDocument rename(String name) {
        return new DatasetDocument(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetDocument rename(Name name) {
        return new DatasetDocument(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
