/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.DatasetQaReferenceRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 数据集问答对引用关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetQaReference extends TableImpl<DatasetQaReferenceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>dataset_qa_reference</code>
     */
    public static final DatasetQaReference DATASET_QA_REFERENCE = new DatasetQaReference();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatasetQaReferenceRecord> getRecordType() {
        return DatasetQaReferenceRecord.class;
    }

    /**
     * The column <code>dataset_qa_reference.id</code>.
     */
    public final TableField<DatasetQaReferenceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>dataset_qa_reference.reference_id</code>. 引用ID；由item_id/file_id/path确定
     */
    public final TableField<DatasetQaReferenceRecord, String> REFERENCE_ID = createField(DSL.name("reference_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "引用ID；由item_id/file_id/path确定");

    /**
     * The column <code>dataset_qa_reference.item_id</code>. 问答对ID
     */
    public final TableField<DatasetQaReferenceRecord, String> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "问答对ID");

    /**
     * The column <code>dataset_qa_reference.dataset_id</code>. 数据集ID
     */
    public final TableField<DatasetQaReferenceRecord, String> DATASET_ID = createField(DSL.name("dataset_id"), SQLDataType.VARCHAR(256).nullable(false), this, "数据集ID");

    /**
     * The column <code>dataset_qa_reference.file_id</code>. 文件ID
     */
    public final TableField<DatasetQaReferenceRecord, String> FILE_ID = createField(DSL.name("file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件ID");

    /**
     * The column <code>dataset_qa_reference.path</code>. 位置信息
     */
    public final TableField<DatasetQaReferenceRecord, String> PATH = createField(DSL.name("path"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "位置信息");

    /**
     * The column <code>dataset_qa_reference.cuid</code>.
     */
    public final TableField<DatasetQaReferenceRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dataset_qa_reference.cu_name</code>.
     */
    public final TableField<DatasetQaReferenceRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dataset_qa_reference.ctime</code>.
     */
    public final TableField<DatasetQaReferenceRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dataset_qa_reference.muid</code>.
     */
    public final TableField<DatasetQaReferenceRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dataset_qa_reference.mu_name</code>.
     */
    public final TableField<DatasetQaReferenceRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dataset_qa_reference.mtime</code>.
     */
    public final TableField<DatasetQaReferenceRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dataset_qa_reference.status</code>. 引用是否被删除，0表示未删除，-1表示已删除
     */
    public final TableField<DatasetQaReferenceRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "引用是否被删除，0表示未删除，-1表示已删除");

    private DatasetQaReference(Name alias, Table<DatasetQaReferenceRecord> aliased) {
        this(alias, aliased, null);
    }

    private DatasetQaReference(Name alias, Table<DatasetQaReferenceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("数据集问答对引用关系表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>dataset_qa_reference</code> table reference
     */
    public DatasetQaReference(String alias) {
        this(DSL.name(alias), DATASET_QA_REFERENCE);
    }

    /**
     * Create an aliased <code>dataset_qa_reference</code> table reference
     */
    public DatasetQaReference(Name alias) {
        this(alias, DATASET_QA_REFERENCE);
    }

    /**
     * Create a <code>dataset_qa_reference</code> table reference
     */
    public DatasetQaReference() {
        this(DSL.name("dataset_qa_reference"), null);
    }

    public <O extends Record> DatasetQaReference(Table<O> child, ForeignKey<O, DatasetQaReferenceRecord> key) {
        super(child, key, DATASET_QA_REFERENCE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATASET_QA_REFERENCE_IDX_CTIME, Indexes.DATASET_QA_REFERENCE_IDX_DATASET_ID, Indexes.DATASET_QA_REFERENCE_IDX_ITEM_ID, Indexes.DATASET_QA_REFERENCE_IDX_MTIME);
    }

    @Override
    public Identity<DatasetQaReferenceRecord, Long> getIdentity() {
        return (Identity<DatasetQaReferenceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DatasetQaReferenceRecord> getPrimaryKey() {
        return Keys.KEY_DATASET_QA_REFERENCE_PRIMARY;
    }

    @Override
    public List<UniqueKey<DatasetQaReferenceRecord>> getKeys() {
        return Arrays.<UniqueKey<DatasetQaReferenceRecord>>asList(Keys.KEY_DATASET_QA_REFERENCE_PRIMARY, Keys.KEY_DATASET_QA_REFERENCE_IDX_REFERENCE_ID);
    }

    @Override
    public DatasetQaReference as(String alias) {
        return new DatasetQaReference(DSL.name(alias), this);
    }

    @Override
    public DatasetQaReference as(Name alias) {
        return new DatasetQaReference(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetQaReference rename(String name) {
        return new DatasetQaReference(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetQaReference rename(Name name) {
        return new DatasetQaReference(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
