/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.DatasetQaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 问答数据集表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetQa extends TableImpl<DatasetQaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>dataset_qa</code>
     */
    public static final DatasetQa DATASET_QA = new DatasetQa();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatasetQaRecord> getRecordType() {
        return DatasetQaRecord.class;
    }

    /**
     * The column <code>dataset_qa.id</code>.
     */
    public final TableField<DatasetQaRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>dataset_qa.item_id</code>. QA的ID
     */
    public final TableField<DatasetQaRecord, String> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "QA的ID");

    /**
     * The column <code>dataset_qa.dataset_sharding_key</code>. 数据集分片的key
     */
    public final TableField<DatasetQaRecord, String> DATASET_SHARDING_KEY = createField(DSL.name("dataset_sharding_key"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "数据集分片的key");

    /**
     * The column <code>dataset_qa.dataset_id</code>. 数据集ID
     */
    public final TableField<DatasetQaRecord, String> DATASET_ID = createField(DSL.name("dataset_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "数据集ID");

    /**
     * The column <code>dataset_qa.question</code>. 问题
     */
    public final TableField<DatasetQaRecord, String> QUESTION = createField(DSL.name("question"), SQLDataType.CLOB, this, "问题");

    /**
     * The column <code>dataset_qa.similar_q1</code>. 相似问1
     */
    public final TableField<DatasetQaRecord, String> SIMILAR_Q1 = createField(DSL.name("similar_q1"), SQLDataType.CLOB, this, "相似问1");

    /**
     * The column <code>dataset_qa.similar_q2</code>. 相似问2
     */
    public final TableField<DatasetQaRecord, String> SIMILAR_Q2 = createField(DSL.name("similar_q2"), SQLDataType.CLOB, this, "相似问2");

    /**
     * The column <code>dataset_qa.similar_q3</code>. 相似问3
     */
    public final TableField<DatasetQaRecord, String> SIMILAR_Q3 = createField(DSL.name("similar_q3"), SQLDataType.CLOB, this, "相似问3");

    /**
     * The column <code>dataset_qa.answer</code>. 答案
     */
    public final TableField<DatasetQaRecord, String> ANSWER = createField(DSL.name("answer"), SQLDataType.CLOB, this, "答案");

    /**
     * The column <code>dataset_qa.reasoning</code>. 推理过程/解题思路
     */
    public final TableField<DatasetQaRecord, String> REASONING = createField(DSL.name("reasoning"), SQLDataType.VARCHAR(4096).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "推理过程/解题思路");

    /**
     * The column <code>dataset_qa.tags</code>. 标签信息冗余存储，格式：[{"tag_id":"","name":""}]
     */
    public final TableField<DatasetQaRecord, String> TAGS = createField(DSL.name("tags"), SQLDataType.VARCHAR(8192), this, "标签信息冗余存储，格式：[{\"tag_id\":\"\",\"name\":\"\"}]");

    /**
     * The column <code>dataset_qa.cuid</code>.
     */
    public final TableField<DatasetQaRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dataset_qa.cu_name</code>.
     */
    public final TableField<DatasetQaRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dataset_qa.ctime</code>.
     */
    public final TableField<DatasetQaRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dataset_qa.muid</code>.
     */
    public final TableField<DatasetQaRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dataset_qa.mu_name</code>.
     */
    public final TableField<DatasetQaRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dataset_qa.mtime</code>.
     */
    public final TableField<DatasetQaRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dataset_qa.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public final TableField<DatasetQaRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "数据集是否被删除，0表示未删除，-1表示已删除");

    private DatasetQa(Name alias, Table<DatasetQaRecord> aliased) {
        this(alias, aliased, null);
    }

    private DatasetQa(Name alias, Table<DatasetQaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("问答数据集表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>dataset_qa</code> table reference
     */
    public DatasetQa(String alias) {
        this(DSL.name(alias), DATASET_QA);
    }

    /**
     * Create an aliased <code>dataset_qa</code> table reference
     */
    public DatasetQa(Name alias) {
        this(alias, DATASET_QA);
    }

    /**
     * Create a <code>dataset_qa</code> table reference
     */
    public DatasetQa() {
        this(DSL.name("dataset_qa"), null);
    }

    public <O extends Record> DatasetQa(Table<O> child, ForeignKey<O, DatasetQaRecord> key) {
        super(child, key, DATASET_QA);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATASET_QA_IDX_CTIME, Indexes.DATASET_QA_IDX_DATASET_ITEM, Indexes.DATASET_QA_IDX_MTIME);
    }

    @Override
    public Identity<DatasetQaRecord, Long> getIdentity() {
        return (Identity<DatasetQaRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DatasetQaRecord> getPrimaryKey() {
        return Keys.KEY_DATASET_QA_PRIMARY;
    }

    @Override
    public List<UniqueKey<DatasetQaRecord>> getKeys() {
        return Arrays.<UniqueKey<DatasetQaRecord>>asList(Keys.KEY_DATASET_QA_PRIMARY, Keys.KEY_DATASET_QA_IDX_ITEM_ID);
    }

    @Override
    public DatasetQa as(String alias) {
        return new DatasetQa(DSL.name(alias), this);
    }

    @Override
    public DatasetQa as(Name alias) {
        return new DatasetQa(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetQa rename(String name) {
        return new DatasetQa(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasetQa rename(Name name) {
        return new DatasetQa(name, null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, String, String, String, String, String, String, String, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }
}
