/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.FileUploadRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 分片上传会话表（低频，不分表）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileUpload extends TableImpl<FileUploadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>file_upload</code>
     */
    public static final FileUpload FILE_UPLOAD = new FileUpload();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileUploadRecord> getRecordType() {
        return FileUploadRecord.class;
    }

    /**
     * The column <code>file_upload.id</code>. 自增主键
     */
    public final TableField<FileUploadRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "自增主键");

    /**
     * The column <code>file_upload.upload_id</code>. 上传会话ID，upload-开头
     */
    public final TableField<FileUploadRecord, String> UPLOAD_ID = createField(DSL.name("upload_id"), SQLDataType.VARCHAR(64).nullable(false), this, "上传会话ID，upload-开头");

    /**
     * The column <code>file_upload.space_code</code>. 所属空间
     */
    public final TableField<FileUploadRecord, String> SPACE_CODE = createField(DSL.name("space_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "所属空间");

    /**
     * The column <code>file_upload.ak_code</code>. 发起方AK
     */
    public final TableField<FileUploadRecord, String> AK_CODE = createField(DSL.name("ak_code"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "发起方AK");

    /**
     * The column <code>file_upload.file_id</code>. 预生成的文件ID
     */
    public final TableField<FileUploadRecord, String> FILE_ID = createField(DSL.name("file_id"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "预生成的文件ID");

    /**
     * The column <code>file_upload.filename</code>. 文件名
     */
    public final TableField<FileUploadRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(512).nullable(false), this, "文件名");

    /**
     * The column <code>file_upload.extension</code>. 扩展名
     */
    public final TableField<FileUploadRecord, String> EXTENSION = createField(DSL.name("extension"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "扩展名");

    /**
     * The column <code>file_upload.purpose</code>. 用途
     */
    public final TableField<FileUploadRecord, String> PURPOSE = createField(DSL.name("purpose"), SQLDataType.VARCHAR(32).nullable(false), this, "用途");

    /**
     * The column <code>file_upload.mime_type</code>. MIME类型
     */
    public final TableField<FileUploadRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "MIME类型");

    /**
     * The column <code>file_upload.type</code>. 文件类型
     */
    public final TableField<FileUploadRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件类型");

    /**
     * The column <code>file_upload.charset</code>. 字符集
     */
    public final TableField<FileUploadRecord, String> CHARSET = createField(DSL.name("charset"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "字符集");

    /**
     * The column <code>file_upload.bucket</code>. 目标bucket
     */
    public final TableField<FileUploadRecord, String> BUCKET = createField(DSL.name("bucket"), SQLDataType.VARCHAR(64).nullable(false), this, "目标bucket");

    /**
     * The column <code>file_upload.path</code>. 目标对象key
     */
    public final TableField<FileUploadRecord, String> PATH = createField(DSL.name("path"), SQLDataType.VARCHAR(512).nullable(false), this, "目标对象key");

    /**
     * The column <code>file_upload.declared_bytes</code>. 声明的文件总大小
     */
    public final TableField<FileUploadRecord, Long> DECLARED_BYTES = createField(DSL.name("declared_bytes"), SQLDataType.BIGINT.nullable(false), this, "声明的文件总大小");

    /**
     * The column <code>file_upload.storage_upload_id</code>. 底层multipart uploadId
     */
    public final TableField<FileUploadRecord, String> STORAGE_UPLOAD_ID = createField(DSL.name("storage_upload_id"), SQLDataType.VARCHAR(256).nullable(false), this, "底层multipart uploadId");

    /**
     * The column <code>file_upload.ancestor_id</code>. 目标目录fileId
     */
    public final TableField<FileUploadRecord, String> ANCESTOR_ID = createField(DSL.name("ancestor_id"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "目标目录fileId");

    /**
     * The column <code>file_upload.metadata</code>. 业务元数据JSON
     */
    public final TableField<FileUploadRecord, String> METADATA = createField(DSL.name("metadata"), SQLDataType.CLOB, this, "业务元数据JSON");

    /**
     * The column <code>file_upload.description</code>. 描述
     */
    public final TableField<FileUploadRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "描述");

    /**
     * The column <code>file_upload.cities</code>. 城市JSON
     */
    public final TableField<FileUploadRecord, String> CITIES = createField(DSL.name("cities"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "城市JSON");

    /**
     * The column <code>file_upload.tags</code>. 标签JSON
     */
    public final TableField<FileUploadRecord, String> TAGS = createField(DSL.name("tags"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "标签JSON");

    /**
     * The column <code>file_upload.status</code>. PENDING/COMPLETING/COMPLETED/CANCELLED
     */
    public final TableField<FileUploadRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("PENDING", SQLDataType.VARCHAR)), this, "PENDING/COMPLETING/COMPLETED/CANCELLED");

    /**
     * The column <code>file_upload.expires_at</code>. 会话过期时间
     */
    public final TableField<FileUploadRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "会话过期时间");

    /**
     * The column <code>file_upload.cuid</code>. 创建人ID
     */
    public final TableField<FileUploadRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "创建人ID");

    /**
     * The column <code>file_upload.cu_name</code>. 创建人姓名
     */
    public final TableField<FileUploadRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "创建人姓名");

    /**
     * The column <code>file_upload.ctime</code>. 创建时间
     */
    public final TableField<FileUploadRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>file_upload.mtime</code>. 更新时间
     */
    public final TableField<FileUploadRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "更新时间");

    private FileUpload(Name alias, Table<FileUploadRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileUpload(Name alias, Table<FileUploadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("分片上传会话表（低频，不分表）"), TableOptions.table());
    }

    /**
     * Create an aliased <code>file_upload</code> table reference
     */
    public FileUpload(String alias) {
        this(DSL.name(alias), FILE_UPLOAD);
    }

    /**
     * Create an aliased <code>file_upload</code> table reference
     */
    public FileUpload(Name alias) {
        this(alias, FILE_UPLOAD);
    }

    /**
     * Create a <code>file_upload</code> table reference
     */
    public FileUpload() {
        this(DSL.name("file_upload"), null);
    }

    public <O extends Record> FileUpload(Table<O> child, ForeignKey<O, FileUploadRecord> key) {
        super(child, key, FILE_UPLOAD);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FILE_UPLOAD_IDX_SPACE_STATUS);
    }

    @Override
    public Identity<FileUploadRecord, Long> getIdentity() {
        return (Identity<FileUploadRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileUploadRecord> getPrimaryKey() {
        return Keys.KEY_FILE_UPLOAD_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileUploadRecord>> getKeys() {
        return Arrays.<UniqueKey<FileUploadRecord>>asList(Keys.KEY_FILE_UPLOAD_PRIMARY, Keys.KEY_FILE_UPLOAD_UNIQ_UPLOAD_ID);
    }

    @Override
    public FileUpload as(String alias) {
        return new FileUpload(DSL.name(alias), this);
    }

    @Override
    public FileUpload as(Name alias) {
        return new FileUpload(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileUpload rename(String name) {
        return new FileUpload(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileUpload rename(Name name) {
        return new FileUpload(name, null);
    }
}
