/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.FileProgressRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileProgress extends TableImpl<FileProgressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>file_progress</code>
     */
    public static final FileProgress FILE_PROGRESS = new FileProgress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileProgressRecord> getRecordType() {
        return FileProgressRecord.class;
    }

    /**
     * The column <code>file_progress.id</code>.
     */
    public final TableField<FileProgressRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>file_progress.file_id</code>. 文件id
     */
    public final TableField<FileProgressRecord, String> FILE_ID = createField(DSL.name("file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件id");

    /**
     * The column <code>file_progress.name</code>. 后处理名，一期由服务端枚举指定
     */
    public final TableField<FileProgressRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "后处理名，一期由服务端枚举指定");

    /**
     * The column <code>file_progress.status</code>. 自定义状态，file api维护
     */
    public final TableField<FileProgressRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "自定义状态，file api维护");

    /**
     * The column <code>file_progress.message</code>. 自定义信息，后处理维护
     */
    public final TableField<FileProgressRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "自定义信息，后处理维护");

    /**
     * The column <code>file_progress.percent</code>. 进度,单位百分比,0~100，后处理维护
     */
    public final TableField<FileProgressRecord, Integer> PERCENT = createField(DSL.name("percent"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "进度,单位百分比,0~100，后处理维护");

    /**
     * The column <code>file_progress.cuid</code>.
     */
    public final TableField<FileProgressRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_progress.cu_name</code>.
     */
    public final TableField<FileProgressRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_progress.ctime</code>.
     */
    public final TableField<FileProgressRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>file_progress.muid</code>.
     */
    public final TableField<FileProgressRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_progress.mu_name</code>.
     */
    public final TableField<FileProgressRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_progress.mtime</code>.
     */
    public final TableField<FileProgressRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private FileProgress(Name alias, Table<FileProgressRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileProgress(Name alias, Table<FileProgressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>file_progress</code> table reference
     */
    public FileProgress(String alias) {
        this(DSL.name(alias), FILE_PROGRESS);
    }

    /**
     * Create an aliased <code>file_progress</code> table reference
     */
    public FileProgress(Name alias) {
        this(alias, FILE_PROGRESS);
    }

    /**
     * Create a <code>file_progress</code> table reference
     */
    public FileProgress() {
        this(DSL.name("file_progress"), null);
    }

    public <O extends Record> FileProgress(Table<O> child, ForeignKey<O, FileProgressRecord> key) {
        super(child, key, FILE_PROGRESS);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FILE_PROGRESS_IDX_FILE_ID_NAME);
    }

    @Override
    public Identity<FileProgressRecord, Long> getIdentity() {
        return (Identity<FileProgressRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileProgressRecord> getPrimaryKey() {
        return Keys.KEY_FILE_PROGRESS_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileProgressRecord>> getKeys() {
        return Arrays.<UniqueKey<FileProgressRecord>>asList(Keys.KEY_FILE_PROGRESS_PRIMARY, Keys.KEY_FILE_PROGRESS_FILE_ID);
    }

    @Override
    public FileProgress as(String alias) {
        return new FileProgress(DSL.name(alias), this);
    }

    @Override
    public FileProgress as(Name alias) {
        return new FileProgress(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileProgress rename(String name) {
        return new FileProgress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileProgress rename(Name name) {
        return new FileProgress(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
