/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.FileShardingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileSharding extends TableImpl<FileShardingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>file_sharding</code>
     */
    public static final FileSharding FILE_SHARDING = new FileSharding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileShardingRecord> getRecordType() {
        return FileShardingRecord.class;
    }

    /**
     * The column <code>file_sharding.id</code>.
     */
    public final TableField<FileShardingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>file_sharding.type</code>. 分片类型：temp-临时文件，system-系统文件
     */
    public final TableField<FileShardingRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "分片类型：temp-临时文件，system-系统文件");

    /**
     * The column <code>file_sharding.key</code>. 分表的标识，
     */
    public final TableField<FileShardingRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "分表的标识，");

    /**
     * The column <code>file_sharding.key_time</code>. 当前分片第一条数据的时间，用于索引分片
     */
    public final TableField<FileShardingRecord, LocalDateTime> KEY_TIME = createField(DSL.name("key_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "当前分片第一条数据的时间，用于索引分片");

    /**
     * The column <code>file_sharding.last_key</code>. 上一次分表的标识，用于分表创建并发控制
     */
    public final TableField<FileShardingRecord, String> LAST_KEY = createField(DSL.name("last_key"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "上一次分表的标识，用于分表创建并发控制");

    /**
     * The column <code>file_sharding.count</code>. 分表的记录数量
     */
    public final TableField<FileShardingRecord, Long> COUNT = createField(DSL.name("count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "分表的记录数量");

    /**
     * The column <code>file_sharding.max_count</code>. 分表的最大记录数
如果count&gt;max_count， 创建新表
     */
    public final TableField<FileShardingRecord, Long> MAX_COUNT = createField(DSL.name("max_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("20000000", SQLDataType.BIGINT)), this, "分表的最大记录数\n如果count>max_count， 创建新表");

    /**
     * The column <code>file_sharding.ctime</code>.
     */
    public final TableField<FileShardingRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>file_sharding.cu_name</code>.
     */
    public final TableField<FileShardingRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_sharding.cuid</code>.
     */
    public final TableField<FileShardingRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_sharding.mtime</code>.
     */
    public final TableField<FileShardingRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>file_sharding.mu_name</code>.
     */
    public final TableField<FileShardingRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_sharding.muid</code>.
     */
    public final TableField<FileShardingRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    private FileSharding(Name alias, Table<FileShardingRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileSharding(Name alias, Table<FileShardingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>file_sharding</code> table reference
     */
    public FileSharding(String alias) {
        this(DSL.name(alias), FILE_SHARDING);
    }

    /**
     * Create an aliased <code>file_sharding</code> table reference
     */
    public FileSharding(Name alias) {
        this(alias, FILE_SHARDING);
    }

    /**
     * Create a <code>file_sharding</code> table reference
     */
    public FileSharding() {
        this(DSL.name("file_sharding"), null);
    }

    public <O extends Record> FileSharding(Table<O> child, ForeignKey<O, FileShardingRecord> key) {
        super(child, key, FILE_SHARDING);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FILE_SHARDING_IDX_TYPE_LAST_KEY);
    }

    @Override
    public Identity<FileShardingRecord, Long> getIdentity() {
        return (Identity<FileShardingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileShardingRecord> getPrimaryKey() {
        return Keys.KEY_FILE_SHARDING_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileShardingRecord>> getKeys() {
        return Arrays.<UniqueKey<FileShardingRecord>>asList(Keys.KEY_FILE_SHARDING_PRIMARY, Keys.KEY_FILE_SHARDING_IDX_TYPE_KEY);
    }

    @Override
    public FileSharding as(String alias) {
        return new FileSharding(DSL.name(alias), this);
    }

    @Override
    public FileSharding as(Name alias) {
        return new FileSharding(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileSharding rename(String name) {
        return new FileSharding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileSharding rename(Name name) {
        return new FileSharding(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, LocalDateTime, String, Long, Long, LocalDateTime, String, Long, LocalDateTime, String, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
