/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.FileMappingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileMapping extends TableImpl<FileMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>file_mapping</code>
     */
    public static final FileMapping FILE_MAPPING = new FileMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileMappingRecord> getRecordType() {
        return FileMappingRecord.class;
    }

    /**
     * The column <code>file_mapping.id</code>.
     */
    public final TableField<FileMappingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>file_mapping.file_id</code>.
     */
    public final TableField<FileMappingRecord, String> FILE_ID = createField(DSL.name("file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_mapping.file_id_old</code>. 老的file_id
     */
    public final TableField<FileMappingRecord, String> FILE_ID_OLD = createField(DSL.name("file_id_old"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "老的file_id");

    /**
     * The column <code>file_mapping.cuid</code>.
     */
    public final TableField<FileMappingRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_mapping.cu_name</code>.
     */
    public final TableField<FileMappingRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_mapping.ctime</code>.
     */
    public final TableField<FileMappingRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>file_mapping.muid</code>.
     */
    public final TableField<FileMappingRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_mapping.mu_name</code>.
     */
    public final TableField<FileMappingRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_mapping.mtime</code>.
     */
    public final TableField<FileMappingRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private FileMapping(Name alias, Table<FileMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileMapping(Name alias, Table<FileMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>file_mapping</code> table reference
     */
    public FileMapping(String alias) {
        this(DSL.name(alias), FILE_MAPPING);
    }

    /**
     * Create an aliased <code>file_mapping</code> table reference
     */
    public FileMapping(Name alias) {
        this(alias, FILE_MAPPING);
    }

    /**
     * Create a <code>file_mapping</code> table reference
     */
    public FileMapping() {
        this(DSL.name("file_mapping"), null);
    }

    public <O extends Record> FileMapping(Table<O> child, ForeignKey<O, FileMappingRecord> key) {
        super(child, key, FILE_MAPPING);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FileMappingRecord, Long> getIdentity() {
        return (Identity<FileMappingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileMappingRecord> getPrimaryKey() {
        return Keys.KEY_FILE_MAPPING_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileMappingRecord>> getKeys() {
        return Arrays.<UniqueKey<FileMappingRecord>>asList(Keys.KEY_FILE_MAPPING_PRIMARY, Keys.KEY_FILE_MAPPING_IDX_FILE_ID_NEW_OLD);
    }

    @Override
    public FileMapping as(String alias) {
        return new FileMapping(DSL.name(alias), this);
    }

    @Override
    public FileMapping as(Name alias) {
        return new FileMapping(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileMapping rename(String name) {
        return new FileMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileMapping rename(Name name) {
        return new FileMapping(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
