/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.FileProgressTempRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileProgressTemp extends TableImpl<FileProgressTempRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>file_progress_temp</code>
     */
    public static final FileProgressTemp FILE_PROGRESS_TEMP = new FileProgressTemp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileProgressTempRecord> getRecordType() {
        return FileProgressTempRecord.class;
    }

    /**
     * The column <code>file_progress_temp.id</code>.
     */
    public final TableField<FileProgressTempRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>file_progress_temp.file_id</code>. 文件id
     */
    public final TableField<FileProgressTempRecord, String> FILE_ID = createField(DSL.name("file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件id");

    /**
     * The column <code>file_progress_temp.name</code>. 后处理名，一期由服务端枚举指定
     */
    public final TableField<FileProgressTempRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "后处理名，一期由服务端枚举指定");

    /**
     * The column <code>file_progress_temp.status</code>. 自定义状态，file api维护
     */
    public final TableField<FileProgressTempRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "自定义状态，file api维护");

    /**
     * The column <code>file_progress_temp.message</code>. 自定义信息，后处理维护
     */
    public final TableField<FileProgressTempRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "自定义信息，后处理维护");

    /**
     * The column <code>file_progress_temp.percent</code>. 进度,单位百分比,0~100，后处理维护
     */
    public final TableField<FileProgressTempRecord, Integer> PERCENT = createField(DSL.name("percent"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "进度,单位百分比,0~100，后处理维护");

    /**
     * The column <code>file_progress_temp.cuid</code>.
     */
    public final TableField<FileProgressTempRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_progress_temp.cu_name</code>.
     */
    public final TableField<FileProgressTempRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_progress_temp.ctime</code>.
     */
    public final TableField<FileProgressTempRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>file_progress_temp.muid</code>.
     */
    public final TableField<FileProgressTempRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_progress_temp.mu_name</code>.
     */
    public final TableField<FileProgressTempRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_progress_temp.mtime</code>.
     */
    public final TableField<FileProgressTempRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private FileProgressTemp(Name alias, Table<FileProgressTempRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileProgressTemp(Name alias, Table<FileProgressTempRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>file_progress_temp</code> table reference
     */
    public FileProgressTemp(String alias) {
        this(DSL.name(alias), FILE_PROGRESS_TEMP);
    }

    /**
     * Create an aliased <code>file_progress_temp</code> table reference
     */
    public FileProgressTemp(Name alias) {
        this(alias, FILE_PROGRESS_TEMP);
    }

    /**
     * Create a <code>file_progress_temp</code> table reference
     */
    public FileProgressTemp() {
        this(DSL.name("file_progress_temp"), null);
    }

    public <O extends Record> FileProgressTemp(Table<O> child, ForeignKey<O, FileProgressTempRecord> key) {
        super(child, key, FILE_PROGRESS_TEMP);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FileProgressTempRecord, Long> getIdentity() {
        return (Identity<FileProgressTempRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileProgressTempRecord> getPrimaryKey() {
        return Keys.KEY_FILE_PROGRESS_TEMP_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileProgressTempRecord>> getKeys() {
        return Arrays.<UniqueKey<FileProgressTempRecord>>asList(Keys.KEY_FILE_PROGRESS_TEMP_PRIMARY, Keys.KEY_FILE_PROGRESS_TEMP_IDX_FILE_ID_NAME);
    }

    @Override
    public FileProgressTemp as(String alias) {
        return new FileProgressTemp(DSL.name(alias), this);
    }

    @Override
    public FileProgressTemp as(Name alias) {
        return new FileProgressTemp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileProgressTemp rename(String name) {
        return new FileProgressTemp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileProgressTemp rename(Name name) {
        return new FileProgressTemp(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
