/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Name;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.FileEntryRecord;

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileEntry extends TableImpl<FileEntryRecord> {
    private static final long serialVersionUID = 1L;
    public static final FileEntry FILE_ENTRY = new FileEntry();

    @Override
    public Class<FileEntryRecord> getRecordType() {
        return FileEntryRecord.class;
    }

    public final TableField<FileEntryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
    public final TableField<FileEntryRecord, String> ENTRY_ID = createField(DSL.name("entry_id"), SQLDataType.VARCHAR(96).nullable(false), this, "");
    public final TableField<FileEntryRecord, String> SPACE_CODE = createField(DSL.name("space_code"), SQLDataType.VARCHAR(128).nullable(false), this, "");
    public final TableField<FileEntryRecord, String> PARENT_ENTRY_ID = createField(DSL.name("parent_entry_id"), SQLDataType.VARCHAR(96).nullable(false), this, "");
    public final TableField<FileEntryRecord, String> FILE_ID = createField(DSL.name("file_id"), SQLDataType.VARCHAR(256).nullable(false), this, "");
    public final TableField<FileEntryRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(512).nullable(false), this, "");
    public final TableField<FileEntryRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(16).nullable(false), this, "");
    public final TableField<FileEntryRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false), this, "");
    public final TableField<FileEntryRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");
    public final TableField<FileEntryRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");
    public final TableField<FileEntryRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false), this, "");
    public final TableField<FileEntryRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");
    public final TableField<FileEntryRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private FileEntry(Name alias, Table<FileEntryRecord> aliased) {
        super(alias, null, aliased, null, DSL.comment("文件目录项表"), TableOptions.table());
    }

    public FileEntry(String alias) {
        this(DSL.name(alias), FILE_ENTRY);
    }

    public FileEntry(Name alias) {
        this(alias, FILE_ENTRY);
    }

    public FileEntry() {
        this(DSL.name("file_entry"), null);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FILE_ENTRY_IDX_FILE_ID, Indexes.FILE_ENTRY_IDX_PARENT_ENTRY_ID);
    }

    @Override
    public Identity<FileEntryRecord, Long> getIdentity() {
        return (Identity<FileEntryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileEntryRecord> getPrimaryKey() {
        return Keys.KEY_FILE_ENTRY_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileEntryRecord>> getKeys() {
        return Arrays.asList(Keys.KEY_FILE_ENTRY_PRIMARY, Keys.KEY_FILE_ENTRY_UK_SPACE_ENTRY,
                Keys.KEY_FILE_ENTRY_UK_SPACE_FILE, Keys.KEY_FILE_ENTRY_UK_SPACE_PARENT_NAME);
    }

    @Override
    public FileEntry as(String alias) {
        return new FileEntry(DSL.name(alias), this);
    }

    @Override
    public FileEntry as(Name alias) {
        return new FileEntry(alias, this);
    }

    @Override
    public FileEntry rename(String name) {
        return new FileEntry(DSL.name(name), null);
    }

    @Override
    public FileEntry rename(Name name) {
        return new FileEntry(name, null);
    }
}
