/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.FileClosureRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 文件闭包表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileClosure extends TableImpl<FileClosureRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>file_closure</code>
     */
    public static final FileClosure FILE_CLOSURE = new FileClosure();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileClosureRecord> getRecordType() {
        return FileClosureRecord.class;
    }

    /**
     * The column <code>file_closure.id</code>.
     */
    public final TableField<FileClosureRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>file_closure.ancestor_id</code>. 祖先 file_id
     */
    public final TableField<FileClosureRecord, String> ANCESTOR_ID = createField(DSL.name("ancestor_id"), SQLDataType.VARCHAR(255).nullable(false), this, "祖先 file_id");

    /**
     * The column <code>file_closure.descendant_id</code>. 后代 file_id
     */
    public final TableField<FileClosureRecord, String> DESCENDANT_ID = createField(DSL.name("descendant_id"), SQLDataType.VARCHAR(255).nullable(false), this, "后代 file_id");

    /**
     * The column <code>file_closure.space_code</code>. 组织编码；对标OpenAI organization
     */
    public final TableField<FileClosureRecord, String> SPACE_CODE = createField(DSL.name("space_code"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "组织编码；对标OpenAI organization");

    /**
     * The column <code>file_closure.depth</code>. 深度
     */
    public final TableField<FileClosureRecord, Long> DEPTH = createField(DSL.name("depth"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "深度");

    /**
     * The column <code>file_closure.root_depth</code>. 距离根目录的深度：1为根目录，2为第一级子文件...
     */
    public final TableField<FileClosureRecord, Long> ROOT_DEPTH = createField(DSL.name("root_depth"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("-1", SQLDataType.BIGINT)), this, "距离根目录的深度：1为根目录，2为第一级子文件...");

    /**
     * The column <code>file_closure.cuid</code>.
     */
    public final TableField<FileClosureRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_closure.cu_name</code>.
     */
    public final TableField<FileClosureRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_closure.ctime</code>.
     */
    public final TableField<FileClosureRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>file_closure.muid</code>.
     */
    public final TableField<FileClosureRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_closure.mu_name</code>.
     */
    public final TableField<FileClosureRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_closure.mtime</code>.
     */
    public final TableField<FileClosureRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private FileClosure(Name alias, Table<FileClosureRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileClosure(Name alias, Table<FileClosureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("文件闭包表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>file_closure</code> table reference
     */
    public FileClosure(String alias) {
        this(DSL.name(alias), FILE_CLOSURE);
    }

    /**
     * Create an aliased <code>file_closure</code> table reference
     */
    public FileClosure(Name alias) {
        this(alias, FILE_CLOSURE);
    }

    /**
     * Create a <code>file_closure</code> table reference
     */
    public FileClosure() {
        this(DSL.name("file_closure"), null);
    }

    public <O extends Record> FileClosure(Table<O> child, ForeignKey<O, FileClosureRecord> key) {
        super(child, key, FILE_CLOSURE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FILE_CLOSURE_IDX_ANCESTOR_DEPTH_STATUS, Indexes.FILE_CLOSURE_IDX_DESCENDANT_DEPTH_STATUS, Indexes.FILE_CLOSURE_IDX_SPACE_CODE_ROOT_DEPTH);
    }

    @Override
    public Identity<FileClosureRecord, Long> getIdentity() {
        return (Identity<FileClosureRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileClosureRecord> getPrimaryKey() {
        return Keys.KEY_FILE_CLOSURE_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileClosureRecord>> getKeys() {
        return Arrays.<UniqueKey<FileClosureRecord>>asList(Keys.KEY_FILE_CLOSURE_PRIMARY, Keys.KEY_FILE_CLOSURE_IDX_ANCESTOR_DESCENDANT);
    }

    @Override
    public FileClosure as(String alias) {
        return new FileClosure(DSL.name(alias), this);
    }

    @Override
    public FileClosure as(Name alias) {
        return new FileClosure(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileClosure rename(String name) {
        return new FileClosure(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileClosure rename(Name name) {
        return new FileClosure(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, Long, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
