/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables;


import com.ke.bella.files.db.DefaultSchema;
import com.ke.bella.files.db.Indexes;
import com.ke.bella.files.db.Keys;
import com.ke.bella.files.db.tables.records.FileTempRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileTemp extends TableImpl<FileTempRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>file_temp</code>
     */
    public static final FileTemp FILE_TEMP = new FileTemp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileTempRecord> getRecordType() {
        return FileTempRecord.class;
    }

    /**
     * The column <code>file_temp.id</code>.
     */
    public final TableField<FileTempRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>file_temp.file_id</code>. 文件ID
     */
    public final TableField<FileTempRecord, String> FILE_ID = createField(DSL.name("file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件ID");

    /**
     * The column <code>file_temp.version</code>. 文件版本号, 每次变更+1
     */
    public final TableField<FileTempRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "文件版本号, 每次变更+1");

    /**
     * The column <code>file_temp.filename</code>. 文件名
     */
    public final TableField<FileTempRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件名");

    /**
     * The column <code>file_temp.is_dir</code>. 是否为目录：1为目录，0为文件
     */
    public final TableField<FileTempRecord, Integer> IS_DIR = createField(DSL.name("is_dir"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "是否为目录：1为目录，0为文件");

    /**
     * The column <code>file_temp.extension</code>. extension
     */
    public final TableField<FileTempRecord, String> EXTENSION = createField(DSL.name("extension"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "extension");

    /**
     * The column <code>file_temp.mime_type</code>. mime type
     */
    public final TableField<FileTempRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "mime type");

    /**
     * The column <code>file_temp.type</code>. subtype of mime type, also known as file type
     */
    public final TableField<FileTempRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "subtype of mime type, also known as file type");

    /**
     * The column <code>file_temp.bucket</code>. 存储的地方
     */
    public final TableField<FileTempRecord, String> BUCKET = createField(DSL.name("bucket"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "存储的地方");

    /**
     * The column <code>file_temp.path</code>. 文件路径
     */
    public final TableField<FileTempRecord, String> PATH = createField(DSL.name("path"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件路径");

    /**
     * The column <code>file_temp.bytes</code>. 文件大小；单位：字节
     */
    public final TableField<FileTempRecord, Long> BYTES = createField(DSL.name("bytes"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "文件大小；单位：字节");

    /**
     * The column <code>file_temp.space_code</code>. 组织编码；对标OpenAI organization
     */
    public final TableField<FileTempRecord, String> SPACE_CODE = createField(DSL.name("space_code"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "组织编码；对标OpenAI organization");

    /**
     * The column <code>file_temp.purpose</code>. 文件目的，参考OpenAI
     */
    public final TableField<FileTempRecord, String> PURPOSE = createField(DSL.name("purpose"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "文件目的，参考OpenAI");

    /**
     * The column <code>file_temp.cuid</code>.
     */
    public final TableField<FileTempRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_temp.cu_name</code>.
     */
    public final TableField<FileTempRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_temp.ctime</code>.
     */
    public final TableField<FileTempRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>file_temp.muid</code>.
     */
    public final TableField<FileTempRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>file_temp.mu_name</code>.
     */
    public final TableField<FileTempRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_temp.mtime</code>.
     */
    public final TableField<FileTempRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>file_temp.meta_data</code>.
     */
    public final TableField<FileTempRecord, String> META_DATA = createField(DSL.name("meta_data"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>file_temp.status</code>. 文件是否被删除，0表示未删除，-1表示已删除
     */
    public final TableField<FileTempRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "文件是否被删除，0表示未删除，-1表示已删除");

    /**
     * The column <code>file_temp.ak_code</code>.
     */
    public final TableField<FileTempRecord, String> AK_CODE = createField(DSL.name("ak_code"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>file_temp.broadcast_status</code>. 文件是否被广播成功，0表示广播失败，1表示广播成功
     */
    public final TableField<FileTempRecord, Long> BROADCAST_STATUS = createField(DSL.name("broadcast_status"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "文件是否被广播成功，0表示广播失败，1表示广播成功");

    /**
     * The column <code>file_temp.dom_tree_file_id</code>. DOM tree的文件ID
     */
    public final TableField<FileTempRecord, String> DOM_TREE_FILE_ID = createField(DSL.name("dom_tree_file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "DOM tree的文件ID");

    /**
     * The column <code>file_temp.pdf_file_id</code>. PDF的文件ID
     */
    public final TableField<FileTempRecord, String> PDF_FILE_ID = createField(DSL.name("pdf_file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "PDF的文件ID");

    /**
     * The column <code>file_temp.description</code>. 描述
     */
    public final TableField<FileTempRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "描述");

    /**
     * The column <code>file_temp.cities</code>. 作用城市,示例["北京","上海"]
     */
    public final TableField<FileTempRecord, String> CITIES = createField(DSL.name("cities"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "作用城市,示例[\"北京\",\"上海\"]");

    /**
     * The column <code>file_temp.tags</code>. 标签,示例["tag1","tag2"]
     */
    public final TableField<FileTempRecord, String> TAGS = createField(DSL.name("tags"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "标签,示例[\"tag1\",\"tag2\"]");

    private FileTemp(Name alias, Table<FileTempRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileTemp(Name alias, Table<FileTempRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>file_temp</code> table reference
     */
    public FileTemp(String alias) {
        this(DSL.name(alias), FILE_TEMP);
    }

    /**
     * Create an aliased <code>file_temp</code> table reference
     */
    public FileTemp(Name alias) {
        this(alias, FILE_TEMP);
    }

    /**
     * Create a <code>file_temp</code> table reference
     */
    public FileTemp() {
        this(DSL.name("file_temp"), null);
    }

    public <O extends Record> FileTemp(Table<O> child, ForeignKey<O, FileTempRecord> key) {
        super(child, key, FILE_TEMP);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FILE_TEMP_IDX_CTIME, Indexes.FILE_TEMP_IDX_DOM_TREE_FILE_ID, Indexes.FILE_TEMP_IDX_FILENAME_STATUS, Indexes.FILE_TEMP_IDX_PDF_FILE_ID, Indexes.FILE_TEMP_IDX_SPACE_PURPOSE);
    }

    @Override
    public Identity<FileTempRecord, Long> getIdentity() {
        return (Identity<FileTempRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileTempRecord> getPrimaryKey() {
        return Keys.KEY_FILE_TEMP_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileTempRecord>> getKeys() {
        return Arrays.<UniqueKey<FileTempRecord>>asList(Keys.KEY_FILE_TEMP_PRIMARY, Keys.KEY_FILE_TEMP_IDX_FILE_SPACE);
    }

    @Override
    public FileTemp as(String alias) {
        return new FileTemp(DSL.name(alias), this);
    }

    @Override
    public FileTemp as(Name alias) {
        return new FileTemp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileTemp rename(String name) {
        return new FileTemp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileTemp rename(Name name) {
        return new FileTemp(name, null);
    }
}
