/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.DatasetQa;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 问答数据集表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetQaRecord extends UpdatableRecordImpl<DatasetQaRecord> implements Operator, Record18<Long, String, String, String, String, String, String, String, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>dataset_qa.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>dataset_qa.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dataset_qa.item_id</code>. QA的ID
     */
    public void setItemId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dataset_qa.item_id</code>. QA的ID
     */
    public String getItemId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dataset_qa.dataset_sharding_key</code>. 数据集分片的key
     */
    public void setDatasetShardingKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dataset_qa.dataset_sharding_key</code>. 数据集分片的key
     */
    public String getDatasetShardingKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dataset_qa.dataset_id</code>. 数据集ID
     */
    public void setDatasetId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dataset_qa.dataset_id</code>. 数据集ID
     */
    public String getDatasetId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dataset_qa.question</code>. 问题
     */
    public void setQuestion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dataset_qa.question</code>. 问题
     */
    public String getQuestion() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dataset_qa.similar_q1</code>. 相似问1
     */
    public void setSimilarQ1(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dataset_qa.similar_q1</code>. 相似问1
     */
    public String getSimilarQ1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dataset_qa.similar_q2</code>. 相似问2
     */
    public void setSimilarQ2(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>dataset_qa.similar_q2</code>. 相似问2
     */
    public String getSimilarQ2() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dataset_qa.similar_q3</code>. 相似问3
     */
    public void setSimilarQ3(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>dataset_qa.similar_q3</code>. 相似问3
     */
    public String getSimilarQ3() {
        return (String) get(7);
    }

    /**
     * Setter for <code>dataset_qa.answer</code>. 答案
     */
    public void setAnswer(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>dataset_qa.answer</code>. 答案
     */
    public String getAnswer() {
        return (String) get(8);
    }

    /**
     * Setter for <code>dataset_qa.reasoning</code>. 推理过程/解题思路
     */
    public void setReasoning(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>dataset_qa.reasoning</code>. 推理过程/解题思路
     */
    public String getReasoning() {
        return (String) get(9);
    }

    /**
     * Setter for <code>dataset_qa.tags</code>. 标签信息冗余存储，格式：[{"tag_id":"","name":""}]
     */
    public void setTags(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>dataset_qa.tags</code>. 标签信息冗余存储，格式：[{"tag_id":"","name":""}]
     */
    public String getTags() {
        return (String) get(10);
    }

    /**
     * Setter for <code>dataset_qa.cuid</code>.
     */
    public void setCuid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>dataset_qa.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>dataset_qa.cu_name</code>.
     */
    public void setCuName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>dataset_qa.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>dataset_qa.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>dataset_qa.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>dataset_qa.muid</code>.
     */
    public void setMuid(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>dataset_qa.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>dataset_qa.mu_name</code>.
     */
    public void setMuName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>dataset_qa.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>dataset_qa.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>dataset_qa.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>dataset_qa.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>dataset_qa.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, String, String, String, String, String, String, String, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, String, String, String, String, String, String, String, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DatasetQa.DATASET_QA.ID;
    }

    @Override
    public Field<String> field2() {
        return DatasetQa.DATASET_QA.ITEM_ID;
    }

    @Override
    public Field<String> field3() {
        return DatasetQa.DATASET_QA.DATASET_SHARDING_KEY;
    }

    @Override
    public Field<String> field4() {
        return DatasetQa.DATASET_QA.DATASET_ID;
    }

    @Override
    public Field<String> field5() {
        return DatasetQa.DATASET_QA.QUESTION;
    }

    @Override
    public Field<String> field6() {
        return DatasetQa.DATASET_QA.SIMILAR_Q1;
    }

    @Override
    public Field<String> field7() {
        return DatasetQa.DATASET_QA.SIMILAR_Q2;
    }

    @Override
    public Field<String> field8() {
        return DatasetQa.DATASET_QA.SIMILAR_Q3;
    }

    @Override
    public Field<String> field9() {
        return DatasetQa.DATASET_QA.ANSWER;
    }

    @Override
    public Field<String> field10() {
        return DatasetQa.DATASET_QA.REASONING;
    }

    @Override
    public Field<String> field11() {
        return DatasetQa.DATASET_QA.TAGS;
    }

    @Override
    public Field<Long> field12() {
        return DatasetQa.DATASET_QA.CUID;
    }

    @Override
    public Field<String> field13() {
        return DatasetQa.DATASET_QA.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return DatasetQa.DATASET_QA.CTIME;
    }

    @Override
    public Field<Long> field15() {
        return DatasetQa.DATASET_QA.MUID;
    }

    @Override
    public Field<String> field16() {
        return DatasetQa.DATASET_QA.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return DatasetQa.DATASET_QA.MTIME;
    }

    @Override
    public Field<Integer> field18() {
        return DatasetQa.DATASET_QA.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getItemId();
    }

    @Override
    public String component3() {
        return getDatasetShardingKey();
    }

    @Override
    public String component4() {
        return getDatasetId();
    }

    @Override
    public String component5() {
        return getQuestion();
    }

    @Override
    public String component6() {
        return getSimilarQ1();
    }

    @Override
    public String component7() {
        return getSimilarQ2();
    }

    @Override
    public String component8() {
        return getSimilarQ3();
    }

    @Override
    public String component9() {
        return getAnswer();
    }

    @Override
    public String component10() {
        return getReasoning();
    }

    @Override
    public String component11() {
        return getTags();
    }

    @Override
    public Long component12() {
        return getCuid();
    }

    @Override
    public String component13() {
        return getCuName();
    }

    @Override
    public LocalDateTime component14() {
        return getCtime();
    }

    @Override
    public Long component15() {
        return getMuid();
    }

    @Override
    public String component16() {
        return getMuName();
    }

    @Override
    public LocalDateTime component17() {
        return getMtime();
    }

    @Override
    public Integer component18() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getItemId();
    }

    @Override
    public String value3() {
        return getDatasetShardingKey();
    }

    @Override
    public String value4() {
        return getDatasetId();
    }

    @Override
    public String value5() {
        return getQuestion();
    }

    @Override
    public String value6() {
        return getSimilarQ1();
    }

    @Override
    public String value7() {
        return getSimilarQ2();
    }

    @Override
    public String value8() {
        return getSimilarQ3();
    }

    @Override
    public String value9() {
        return getAnswer();
    }

    @Override
    public String value10() {
        return getReasoning();
    }

    @Override
    public String value11() {
        return getTags();
    }

    @Override
    public Long value12() {
        return getCuid();
    }

    @Override
    public String value13() {
        return getCuName();
    }

    @Override
    public LocalDateTime value14() {
        return getCtime();
    }

    @Override
    public Long value15() {
        return getMuid();
    }

    @Override
    public String value16() {
        return getMuName();
    }

    @Override
    public LocalDateTime value17() {
        return getMtime();
    }

    @Override
    public Integer value18() {
        return getStatus();
    }

    @Override
    public DatasetQaRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DatasetQaRecord value2(String value) {
        setItemId(value);
        return this;
    }

    @Override
    public DatasetQaRecord value3(String value) {
        setDatasetShardingKey(value);
        return this;
    }

    @Override
    public DatasetQaRecord value4(String value) {
        setDatasetId(value);
        return this;
    }

    @Override
    public DatasetQaRecord value5(String value) {
        setQuestion(value);
        return this;
    }

    @Override
    public DatasetQaRecord value6(String value) {
        setSimilarQ1(value);
        return this;
    }

    @Override
    public DatasetQaRecord value7(String value) {
        setSimilarQ2(value);
        return this;
    }

    @Override
    public DatasetQaRecord value8(String value) {
        setSimilarQ3(value);
        return this;
    }

    @Override
    public DatasetQaRecord value9(String value) {
        setAnswer(value);
        return this;
    }

    @Override
    public DatasetQaRecord value10(String value) {
        setReasoning(value);
        return this;
    }

    @Override
    public DatasetQaRecord value11(String value) {
        setTags(value);
        return this;
    }

    @Override
    public DatasetQaRecord value12(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public DatasetQaRecord value13(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public DatasetQaRecord value14(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public DatasetQaRecord value15(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public DatasetQaRecord value16(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public DatasetQaRecord value17(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public DatasetQaRecord value18(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public DatasetQaRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Long value12, String value13, LocalDateTime value14, Long value15, String value16, LocalDateTime value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetQaRecord
     */
    public DatasetQaRecord() {
        super(DatasetQa.DATASET_QA);
    }

    /**
     * Create a detached, initialised DatasetQaRecord
     */
    public DatasetQaRecord(Long id, String itemId, String datasetShardingKey, String datasetId, String question, String similarQ1, String similarQ2, String similarQ3, String answer, String reasoning, String tags, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime, Integer status) {
        super(DatasetQa.DATASET_QA);

        setId(id);
        setItemId(itemId);
        setDatasetShardingKey(datasetShardingKey);
        setDatasetId(datasetId);
        setQuestion(question);
        setSimilarQ1(similarQ1);
        setSimilarQ2(similarQ2);
        setSimilarQ3(similarQ3);
        setAnswer(answer);
        setReasoning(reasoning);
        setTags(tags);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
        setStatus(status);
    }
}
