/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.DatasetDocument;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文档数据集表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetDocumentRecord extends UpdatableRecordImpl<DatasetDocumentRecord> implements Operator, Record11<Long, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>dataset_document.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>dataset_document.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dataset_document.dataset_sharding_key</code>. 数据集分片的key
     */
    public void setDatasetShardingKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dataset_document.dataset_sharding_key</code>. 数据集分片的key
     */
    public String getDatasetShardingKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dataset_document.dataset_id</code>. 数据集ID
     */
    public void setDatasetId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dataset_document.dataset_id</code>. 数据集ID
     */
    public String getDatasetId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dataset_document.file_id</code>. 文件ID，作为document的主键
     */
    public void setFileId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dataset_document.file_id</code>. 文件ID，作为document的主键
     */
    public String getFileId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dataset_document.cuid</code>.
     */
    public void setCuid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>dataset_document.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>dataset_document.cu_name</code>.
     */
    public void setCuName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dataset_document.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dataset_document.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>dataset_document.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>dataset_document.muid</code>.
     */
    public void setMuid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>dataset_document.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>dataset_document.mu_name</code>.
     */
    public void setMuName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>dataset_document.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>dataset_document.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>dataset_document.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>dataset_document.status</code>. 文档是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>dataset_document.status</code>. 文档是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DatasetDocument.DATASET_DOCUMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return DatasetDocument.DATASET_DOCUMENT.DATASET_SHARDING_KEY;
    }

    @Override
    public Field<String> field3() {
        return DatasetDocument.DATASET_DOCUMENT.DATASET_ID;
    }

    @Override
    public Field<String> field4() {
        return DatasetDocument.DATASET_DOCUMENT.FILE_ID;
    }

    @Override
    public Field<Long> field5() {
        return DatasetDocument.DATASET_DOCUMENT.CUID;
    }

    @Override
    public Field<String> field6() {
        return DatasetDocument.DATASET_DOCUMENT.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return DatasetDocument.DATASET_DOCUMENT.CTIME;
    }

    @Override
    public Field<Long> field8() {
        return DatasetDocument.DATASET_DOCUMENT.MUID;
    }

    @Override
    public Field<String> field9() {
        return DatasetDocument.DATASET_DOCUMENT.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return DatasetDocument.DATASET_DOCUMENT.MTIME;
    }

    @Override
    public Field<Integer> field11() {
        return DatasetDocument.DATASET_DOCUMENT.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDatasetShardingKey();
    }

    @Override
    public String component3() {
        return getDatasetId();
    }

    @Override
    public String component4() {
        return getFileId();
    }

    @Override
    public Long component5() {
        return getCuid();
    }

    @Override
    public String component6() {
        return getCuName();
    }

    @Override
    public LocalDateTime component7() {
        return getCtime();
    }

    @Override
    public Long component8() {
        return getMuid();
    }

    @Override
    public String component9() {
        return getMuName();
    }

    @Override
    public LocalDateTime component10() {
        return getMtime();
    }

    @Override
    public Integer component11() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDatasetShardingKey();
    }

    @Override
    public String value3() {
        return getDatasetId();
    }

    @Override
    public String value4() {
        return getFileId();
    }

    @Override
    public Long value5() {
        return getCuid();
    }

    @Override
    public String value6() {
        return getCuName();
    }

    @Override
    public LocalDateTime value7() {
        return getCtime();
    }

    @Override
    public Long value8() {
        return getMuid();
    }

    @Override
    public String value9() {
        return getMuName();
    }

    @Override
    public LocalDateTime value10() {
        return getMtime();
    }

    @Override
    public Integer value11() {
        return getStatus();
    }

    @Override
    public DatasetDocumentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value2(String value) {
        setDatasetShardingKey(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value3(String value) {
        setDatasetId(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value4(String value) {
        setFileId(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value5(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value6(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value7(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value8(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value9(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value10(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord value11(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public DatasetDocumentRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6, LocalDateTime value7, Long value8, String value9, LocalDateTime value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetDocumentRecord
     */
    public DatasetDocumentRecord() {
        super(DatasetDocument.DATASET_DOCUMENT);
    }

    /**
     * Create a detached, initialised DatasetDocumentRecord
     */
    public DatasetDocumentRecord(Long id, String datasetShardingKey, String datasetId, String fileId, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime, Integer status) {
        super(DatasetDocument.DATASET_DOCUMENT);

        setId(id);
        setDatasetShardingKey(datasetShardingKey);
        setDatasetId(datasetId);
        setFileId(fileId);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
        setStatus(status);
    }
}
