/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.DatasetQaReference;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 数据集问答对引用关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetQaReferenceRecord extends UpdatableRecordImpl<DatasetQaReferenceRecord> implements Operator, Record14<Long, String, String, String, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>dataset_qa_reference.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dataset_qa_reference.reference_id</code>. 引用ID；由item_id/file_id/path确定
     */
    public void setReferenceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.reference_id</code>. 引用ID；由item_id/file_id/path确定
     */
    public String getReferenceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dataset_qa_reference.item_id</code>. 问答对ID
     */
    public void setItemId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.item_id</code>. 问答对ID
     */
    public String getItemId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dataset_qa_reference.dataset_id</code>. 数据集ID
     */
    public void setDatasetId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.dataset_id</code>. 数据集ID
     */
    public String getDatasetId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dataset_qa_reference.file_id</code>. 文件ID
     */
    public void setFileId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.file_id</code>. 文件ID
     */
    public String getFileId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dataset_qa_reference.path</code>. 位置信息
     */
    public void setPath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.path</code>. 位置信息
     */
    public String getPath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dataset_qa_reference.snippet</code>. snippet for dataset qa reference
     */
    public void setSnippet(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.snippet</code>. snippet for dataset qa reference
     */
    public String getSnippet() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dataset_qa_reference.cuid</code>.
     */
    public void setCuid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>dataset_qa_reference.cu_name</code>.
     */
    public void setCuName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>dataset_qa_reference.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>dataset_qa_reference.muid</code>.
     */
    public void setMuid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>dataset_qa_reference.mu_name</code>.
     */
    public void setMuName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>dataset_qa_reference.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>dataset_qa_reference.status</code>. 引用是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>dataset_qa_reference.status</code>. 引用是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DatasetQaReference.DATASET_QA_REFERENCE.ID;
    }

    @Override
    public Field<String> field2() {
        return DatasetQaReference.DATASET_QA_REFERENCE.REFERENCE_ID;
    }

    @Override
    public Field<String> field3() {
        return DatasetQaReference.DATASET_QA_REFERENCE.ITEM_ID;
    }

    @Override
    public Field<String> field4() {
        return DatasetQaReference.DATASET_QA_REFERENCE.DATASET_ID;
    }

    @Override
    public Field<String> field5() {
        return DatasetQaReference.DATASET_QA_REFERENCE.FILE_ID;
    }

    @Override
    public Field<String> field6() {
        return DatasetQaReference.DATASET_QA_REFERENCE.PATH;
    }

    @Override
    public Field<String> field7() {
        return DatasetQaReference.DATASET_QA_REFERENCE.SNIPPET;
    }

    @Override
    public Field<Long> field8() {
        return DatasetQaReference.DATASET_QA_REFERENCE.CUID;
    }

    @Override
    public Field<String> field9() {
        return DatasetQaReference.DATASET_QA_REFERENCE.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return DatasetQaReference.DATASET_QA_REFERENCE.CTIME;
    }

    @Override
    public Field<Long> field11() {
        return DatasetQaReference.DATASET_QA_REFERENCE.MUID;
    }

    @Override
    public Field<String> field12() {
        return DatasetQaReference.DATASET_QA_REFERENCE.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return DatasetQaReference.DATASET_QA_REFERENCE.MTIME;
    }

    @Override
    public Field<Integer> field14() {
        return DatasetQaReference.DATASET_QA_REFERENCE.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getReferenceId();
    }

    @Override
    public String component3() {
        return getItemId();
    }

    @Override
    public String component4() {
        return getDatasetId();
    }

    @Override
    public String component5() {
        return getFileId();
    }

    @Override
    public String component6() {
        return getPath();
    }

    @Override
    public String component7() {
        return getSnippet();
    }

    @Override
    public Long component8() {
        return getCuid();
    }

    @Override
    public String component9() {
        return getCuName();
    }

    @Override
    public LocalDateTime component10() {
        return getCtime();
    }

    @Override
    public Long component11() {
        return getMuid();
    }

    @Override
    public String component12() {
        return getMuName();
    }

    @Override
    public LocalDateTime component13() {
        return getMtime();
    }

    @Override
    public Integer component14() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getReferenceId();
    }

    @Override
    public String value3() {
        return getItemId();
    }

    @Override
    public String value4() {
        return getDatasetId();
    }

    @Override
    public String value5() {
        return getFileId();
    }

    @Override
    public String value6() {
        return getPath();
    }

    @Override
    public String value7() {
        return getSnippet();
    }

    @Override
    public Long value8() {
        return getCuid();
    }

    @Override
    public String value9() {
        return getCuName();
    }

    @Override
    public LocalDateTime value10() {
        return getCtime();
    }

    @Override
    public Long value11() {
        return getMuid();
    }

    @Override
    public String value12() {
        return getMuName();
    }

    @Override
    public LocalDateTime value13() {
        return getMtime();
    }

    @Override
    public Integer value14() {
        return getStatus();
    }

    @Override
    public DatasetQaReferenceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value2(String value) {
        setReferenceId(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value3(String value) {
        setItemId(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value4(String value) {
        setDatasetId(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value5(String value) {
        setFileId(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value6(String value) {
        setPath(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value7(String value) {
        setSnippet(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value8(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value9(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value10(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value11(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value12(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value13(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord value14(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public DatasetQaReferenceRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8, String value9, LocalDateTime value10, Long value11, String value12, LocalDateTime value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetQaReferenceRecord
     */
    public DatasetQaReferenceRecord() {
        super(DatasetQaReference.DATASET_QA_REFERENCE);
    }

    /**
     * Create a detached, initialised DatasetQaReferenceRecord
     */
    public DatasetQaReferenceRecord(Long id, String referenceId, String itemId, String datasetId, String fileId, String path, String snippet, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime, Integer status) {
        super(DatasetQaReference.DATASET_QA_REFERENCE);

        setId(id);
        setReferenceId(referenceId);
        setItemId(itemId);
        setDatasetId(datasetId);
        setFileId(fileId);
        setPath(path);
        setSnippet(snippet);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
        setStatus(status);
    }
}
