/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.DatasetSharding;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetShardingRecord extends UpdatableRecordImpl<DatasetShardingRecord> implements Operator, Record12<Long, String, LocalDateTime, String, Long, Long, LocalDateTime, String, Long, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>dataset_sharding.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>dataset_sharding.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dataset_sharding.key</code>. 分表的标识，
对应的表+’_’+key即是实际读写的表
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dataset_sharding.key</code>. 分表的标识，
对应的表+’_’+key即是实际读写的表
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dataset_sharding.key_time</code>. 当前分片第一条数据的时间，用于索引分片
     */
    public void setKeyTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>dataset_sharding.key_time</code>. 当前分片第一条数据的时间，用于索引分片
     */
    public LocalDateTime getKeyTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>dataset_sharding.last_key</code>. 上一次分表的标识，用于分表创建并发控制
     */
    public void setLastKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dataset_sharding.last_key</code>. 上一次分表的标识，用于分表创建并发控制
     */
    public String getLastKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dataset_sharding.count</code>. 分表的记录数量
     */
    public void setCount(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>dataset_sharding.count</code>. 分表的记录数量
     */
    public Long getCount() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>dataset_sharding.max_count</code>. 分表的最大记录数
如果count&gt;max_count， 创建新表
     */
    public void setMaxCount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>dataset_sharding.max_count</code>. 分表的最大记录数
如果count&gt;max_count， 创建新表
     */
    public Long getMaxCount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>dataset_sharding.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>dataset_sharding.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>dataset_sharding.cu_name</code>.
     */
    public void setCuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>dataset_sharding.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>dataset_sharding.cuid</code>.
     */
    public void setCuid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>dataset_sharding.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>dataset_sharding.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>dataset_sharding.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>dataset_sharding.mu_name</code>.
     */
    public void setMuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>dataset_sharding.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>dataset_sharding.muid</code>.
     */
    public void setMuid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>dataset_sharding.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, LocalDateTime, String, Long, Long, LocalDateTime, String, Long, LocalDateTime, String, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, LocalDateTime, String, Long, Long, LocalDateTime, String, Long, LocalDateTime, String, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DatasetSharding.DATASET_SHARDING.ID;
    }

    @Override
    public Field<String> field2() {
        return DatasetSharding.DATASET_SHARDING.KEY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return DatasetSharding.DATASET_SHARDING.KEY_TIME;
    }

    @Override
    public Field<String> field4() {
        return DatasetSharding.DATASET_SHARDING.LAST_KEY;
    }

    @Override
    public Field<Long> field5() {
        return DatasetSharding.DATASET_SHARDING.COUNT;
    }

    @Override
    public Field<Long> field6() {
        return DatasetSharding.DATASET_SHARDING.MAX_COUNT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return DatasetSharding.DATASET_SHARDING.CTIME;
    }

    @Override
    public Field<String> field8() {
        return DatasetSharding.DATASET_SHARDING.CU_NAME;
    }

    @Override
    public Field<Long> field9() {
        return DatasetSharding.DATASET_SHARDING.CUID;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return DatasetSharding.DATASET_SHARDING.MTIME;
    }

    @Override
    public Field<String> field11() {
        return DatasetSharding.DATASET_SHARDING.MU_NAME;
    }

    @Override
    public Field<Long> field12() {
        return DatasetSharding.DATASET_SHARDING.MUID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public LocalDateTime component3() {
        return getKeyTime();
    }

    @Override
    public String component4() {
        return getLastKey();
    }

    @Override
    public Long component5() {
        return getCount();
    }

    @Override
    public Long component6() {
        return getMaxCount();
    }

    @Override
    public LocalDateTime component7() {
        return getCtime();
    }

    @Override
    public String component8() {
        return getCuName();
    }

    @Override
    public Long component9() {
        return getCuid();
    }

    @Override
    public LocalDateTime component10() {
        return getMtime();
    }

    @Override
    public String component11() {
        return getMuName();
    }

    @Override
    public Long component12() {
        return getMuid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public LocalDateTime value3() {
        return getKeyTime();
    }

    @Override
    public String value4() {
        return getLastKey();
    }

    @Override
    public Long value5() {
        return getCount();
    }

    @Override
    public Long value6() {
        return getMaxCount();
    }

    @Override
    public LocalDateTime value7() {
        return getCtime();
    }

    @Override
    public String value8() {
        return getCuName();
    }

    @Override
    public Long value9() {
        return getCuid();
    }

    @Override
    public LocalDateTime value10() {
        return getMtime();
    }

    @Override
    public String value11() {
        return getMuName();
    }

    @Override
    public Long value12() {
        return getMuid();
    }

    @Override
    public DatasetShardingRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value3(LocalDateTime value) {
        setKeyTime(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value4(String value) {
        setLastKey(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value5(Long value) {
        setCount(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value6(Long value) {
        setMaxCount(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value7(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value8(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value9(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value10(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value11(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public DatasetShardingRecord value12(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public DatasetShardingRecord values(Long value1, String value2, LocalDateTime value3, String value4, Long value5, Long value6, LocalDateTime value7, String value8, Long value9, LocalDateTime value10, String value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetShardingRecord
     */
    public DatasetShardingRecord() {
        super(DatasetSharding.DATASET_SHARDING);
    }

    /**
     * Create a detached, initialised DatasetShardingRecord
     */
    public DatasetShardingRecord(Long id, String key, LocalDateTime keyTime, String lastKey, Long count, Long maxCount, LocalDateTime ctime, String cuName, Long cuid, LocalDateTime mtime, String muName, Long muid) {
        super(DatasetSharding.DATASET_SHARDING);

        setId(id);
        setKey(key);
        setKeyTime(keyTime);
        setLastKey(lastKey);
        setCount(count);
        setMaxCount(maxCount);
        setCtime(ctime);
        setCuName(cuName);
        setCuid(cuid);
        setMtime(mtime);
        setMuName(muName);
        setMuid(muid);
    }
}
