/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.Dataset;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 数据集
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetRecord extends UpdatableRecordImpl<DatasetRecord> implements Operator, Record14<Long, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>dataset.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>dataset.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dataset.space_code</code>. 组织编码；对标OpenAI organization
     */
    public void setSpaceCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dataset.space_code</code>. 组织编码；对标OpenAI organization
     */
    public String getSpaceCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dataset.dataset_id</code>. 数据集ID
     */
    public void setDatasetId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dataset.dataset_id</code>. 数据集ID
     */
    public String getDatasetId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dataset.name</code>. 数据集名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dataset.name</code>. 数据集名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dataset.type</code>. 类型；QA：QA类型
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dataset.type</code>. 类型；QA：QA类型
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dataset.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dataset.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dataset.count</code>. 数量
     */
    public void setCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>dataset.count</code>. 数量
     */
    public Long getCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>dataset.cuid</code>.
     */
    public void setCuid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>dataset.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>dataset.cu_name</code>.
     */
    public void setCuName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>dataset.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>dataset.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>dataset.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>dataset.muid</code>.
     */
    public void setMuid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>dataset.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>dataset.mu_name</code>.
     */
    public void setMuName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>dataset.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>dataset.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>dataset.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>dataset.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>dataset.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, String, Long, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Dataset.DATASET.ID;
    }

    @Override
    public Field<String> field2() {
        return Dataset.DATASET.SPACE_CODE;
    }

    @Override
    public Field<String> field3() {
        return Dataset.DATASET.DATASET_ID;
    }

    @Override
    public Field<String> field4() {
        return Dataset.DATASET.NAME;
    }

    @Override
    public Field<String> field5() {
        return Dataset.DATASET.TYPE;
    }

    @Override
    public Field<String> field6() {
        return Dataset.DATASET.REMARK;
    }

    @Override
    public Field<Long> field7() {
        return Dataset.DATASET.COUNT;
    }

    @Override
    public Field<Long> field8() {
        return Dataset.DATASET.CUID;
    }

    @Override
    public Field<String> field9() {
        return Dataset.DATASET.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Dataset.DATASET.CTIME;
    }

    @Override
    public Field<Long> field11() {
        return Dataset.DATASET.MUID;
    }

    @Override
    public Field<String> field12() {
        return Dataset.DATASET.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Dataset.DATASET.MTIME;
    }

    @Override
    public Field<Integer> field14() {
        return Dataset.DATASET.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSpaceCode();
    }

    @Override
    public String component3() {
        return getDatasetId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getRemark();
    }

    @Override
    public Long component7() {
        return getCount();
    }

    @Override
    public Long component8() {
        return getCuid();
    }

    @Override
    public String component9() {
        return getCuName();
    }

    @Override
    public LocalDateTime component10() {
        return getCtime();
    }

    @Override
    public Long component11() {
        return getMuid();
    }

    @Override
    public String component12() {
        return getMuName();
    }

    @Override
    public LocalDateTime component13() {
        return getMtime();
    }

    @Override
    public Integer component14() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSpaceCode();
    }

    @Override
    public String value3() {
        return getDatasetId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getRemark();
    }

    @Override
    public Long value7() {
        return getCount();
    }

    @Override
    public Long value8() {
        return getCuid();
    }

    @Override
    public String value9() {
        return getCuName();
    }

    @Override
    public LocalDateTime value10() {
        return getCtime();
    }

    @Override
    public Long value11() {
        return getMuid();
    }

    @Override
    public String value12() {
        return getMuName();
    }

    @Override
    public LocalDateTime value13() {
        return getMtime();
    }

    @Override
    public Integer value14() {
        return getStatus();
    }

    @Override
    public DatasetRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DatasetRecord value2(String value) {
        setSpaceCode(value);
        return this;
    }

    @Override
    public DatasetRecord value3(String value) {
        setDatasetId(value);
        return this;
    }

    @Override
    public DatasetRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public DatasetRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public DatasetRecord value6(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public DatasetRecord value7(Long value) {
        setCount(value);
        return this;
    }

    @Override
    public DatasetRecord value8(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public DatasetRecord value9(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public DatasetRecord value10(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public DatasetRecord value11(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public DatasetRecord value12(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public DatasetRecord value13(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public DatasetRecord value14(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public DatasetRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Long value7, Long value8, String value9, LocalDateTime value10, Long value11, String value12, LocalDateTime value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatasetRecord
     */
    public DatasetRecord() {
        super(Dataset.DATASET);
    }

    /**
     * Create a detached, initialised DatasetRecord
     */
    public DatasetRecord(Long id, String spaceCode, String datasetId, String name, String type, String remark, Long count, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime, Integer status) {
        super(Dataset.DATASET);

        setId(id);
        setSpaceCode(spaceCode);
        setDatasetId(datasetId);
        setName(name);
        setType(type);
        setRemark(remark);
        setCount(count);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
        setStatus(status);
    }
}
