/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.FileClosure;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 文件闭包表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileClosureRecord extends UpdatableRecordImpl<FileClosureRecord> implements Operator, Record12<Long, String, String, String, Long, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>file_closure.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>file_closure.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>file_closure.ancestor_id</code>. 祖先 file_id
     */
    public void setAncestorId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>file_closure.ancestor_id</code>. 祖先 file_id
     */
    public String getAncestorId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>file_closure.descendant_id</code>. 后代 file_id
     */
    public void setDescendantId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>file_closure.descendant_id</code>. 后代 file_id
     */
    public String getDescendantId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>file_closure.space_code</code>. 组织编码；对标OpenAI organization
     */
    public void setSpaceCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>file_closure.space_code</code>. 组织编码；对标OpenAI organization
     */
    public String getSpaceCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>file_closure.depth</code>. 深度
     */
    public void setDepth(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>file_closure.depth</code>. 深度
     */
    public Long getDepth() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>file_closure.root_depth</code>. 距离根目录的深度：1为根目录，2为第一级子文件...
     */
    public void setRootDepth(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>file_closure.root_depth</code>. 距离根目录的深度：1为根目录，2为第一级子文件...
     */
    public Long getRootDepth() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>file_closure.cuid</code>.
     */
    public void setCuid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>file_closure.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>file_closure.cu_name</code>.
     */
    public void setCuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>file_closure.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>file_closure.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>file_closure.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>file_closure.muid</code>.
     */
    public void setMuid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>file_closure.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>file_closure.mu_name</code>.
     */
    public void setMuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>file_closure.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>file_closure.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>file_closure.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, Long, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, String, Long, Long, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FileClosure.FILE_CLOSURE.ID;
    }

    @Override
    public Field<String> field2() {
        return FileClosure.FILE_CLOSURE.ANCESTOR_ID;
    }

    @Override
    public Field<String> field3() {
        return FileClosure.FILE_CLOSURE.DESCENDANT_ID;
    }

    @Override
    public Field<String> field4() {
        return FileClosure.FILE_CLOSURE.SPACE_CODE;
    }

    @Override
    public Field<Long> field5() {
        return FileClosure.FILE_CLOSURE.DEPTH;
    }

    @Override
    public Field<Long> field6() {
        return FileClosure.FILE_CLOSURE.ROOT_DEPTH;
    }

    @Override
    public Field<Long> field7() {
        return FileClosure.FILE_CLOSURE.CUID;
    }

    @Override
    public Field<String> field8() {
        return FileClosure.FILE_CLOSURE.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return FileClosure.FILE_CLOSURE.CTIME;
    }

    @Override
    public Field<Long> field10() {
        return FileClosure.FILE_CLOSURE.MUID;
    }

    @Override
    public Field<String> field11() {
        return FileClosure.FILE_CLOSURE.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return FileClosure.FILE_CLOSURE.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAncestorId();
    }

    @Override
    public String component3() {
        return getDescendantId();
    }

    @Override
    public String component4() {
        return getSpaceCode();
    }

    @Override
    public Long component5() {
        return getDepth();
    }

    @Override
    public Long component6() {
        return getRootDepth();
    }

    @Override
    public Long component7() {
        return getCuid();
    }

    @Override
    public String component8() {
        return getCuName();
    }

    @Override
    public LocalDateTime component9() {
        return getCtime();
    }

    @Override
    public Long component10() {
        return getMuid();
    }

    @Override
    public String component11() {
        return getMuName();
    }

    @Override
    public LocalDateTime component12() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAncestorId();
    }

    @Override
    public String value3() {
        return getDescendantId();
    }

    @Override
    public String value4() {
        return getSpaceCode();
    }

    @Override
    public Long value5() {
        return getDepth();
    }

    @Override
    public Long value6() {
        return getRootDepth();
    }

    @Override
    public Long value7() {
        return getCuid();
    }

    @Override
    public String value8() {
        return getCuName();
    }

    @Override
    public LocalDateTime value9() {
        return getCtime();
    }

    @Override
    public Long value10() {
        return getMuid();
    }

    @Override
    public String value11() {
        return getMuName();
    }

    @Override
    public LocalDateTime value12() {
        return getMtime();
    }

    @Override
    public FileClosureRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FileClosureRecord value2(String value) {
        setAncestorId(value);
        return this;
    }

    @Override
    public FileClosureRecord value3(String value) {
        setDescendantId(value);
        return this;
    }

    @Override
    public FileClosureRecord value4(String value) {
        setSpaceCode(value);
        return this;
    }

    @Override
    public FileClosureRecord value5(Long value) {
        setDepth(value);
        return this;
    }

    @Override
    public FileClosureRecord value6(Long value) {
        setRootDepth(value);
        return this;
    }

    @Override
    public FileClosureRecord value7(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public FileClosureRecord value8(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public FileClosureRecord value9(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public FileClosureRecord value10(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public FileClosureRecord value11(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public FileClosureRecord value12(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public FileClosureRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6, Long value7, String value8, LocalDateTime value9, Long value10, String value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileClosureRecord
     */
    public FileClosureRecord() {
        super(FileClosure.FILE_CLOSURE);
    }

    /**
     * Create a detached, initialised FileClosureRecord
     */
    public FileClosureRecord(Long id, String ancestorId, String descendantId, String spaceCode, Long depth, Long rootDepth, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(FileClosure.FILE_CLOSURE);

        setId(id);
        setAncestorId(ancestorId);
        setDescendantId(descendantId);
        setSpaceCode(spaceCode);
        setDepth(depth);
        setRootDepth(rootDepth);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }
}
