/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.FileProgressTemp;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileProgressTempRecord extends UpdatableRecordImpl<FileProgressTempRecord> implements Operator, Record12<Long, String, String, String, String, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>file_progress_temp.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>file_progress_temp.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>file_progress_temp.file_id</code>. 文件id
     */
    public void setFileId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>file_progress_temp.file_id</code>. 文件id
     */
    public String getFileId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>file_progress_temp.name</code>. 后处理名，一期由服务端枚举指定
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>file_progress_temp.name</code>. 后处理名，一期由服务端枚举指定
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>file_progress_temp.status</code>. 自定义状态，file api维护
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>file_progress_temp.status</code>. 自定义状态，file api维护
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>file_progress_temp.message</code>. 自定义信息，后处理维护
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>file_progress_temp.message</code>. 自定义信息，后处理维护
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>file_progress_temp.percent</code>. 进度,单位百分比,0~100，后处理维护
     */
    public void setPercent(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>file_progress_temp.percent</code>. 进度,单位百分比,0~100，后处理维护
     */
    public Integer getPercent() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>file_progress_temp.cuid</code>.
     */
    public void setCuid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>file_progress_temp.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>file_progress_temp.cu_name</code>.
     */
    public void setCuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>file_progress_temp.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>file_progress_temp.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>file_progress_temp.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>file_progress_temp.muid</code>.
     */
    public void setMuid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>file_progress_temp.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>file_progress_temp.mu_name</code>.
     */
    public void setMuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>file_progress_temp.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>file_progress_temp.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>file_progress_temp.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, String, String, Integer, Long, String, LocalDateTime, Long, String, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.ID;
    }

    @Override
    public Field<String> field2() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.FILE_ID;
    }

    @Override
    public Field<String> field3() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.NAME;
    }

    @Override
    public Field<String> field4() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.STATUS;
    }

    @Override
    public Field<String> field5() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.MESSAGE;
    }

    @Override
    public Field<Integer> field6() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.PERCENT;
    }

    @Override
    public Field<Long> field7() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.CUID;
    }

    @Override
    public Field<String> field8() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.CTIME;
    }

    @Override
    public Field<Long> field10() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.MUID;
    }

    @Override
    public Field<String> field11() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return FileProgressTemp.FILE_PROGRESS_TEMP.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFileId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getMessage();
    }

    @Override
    public Integer component6() {
        return getPercent();
    }

    @Override
    public Long component7() {
        return getCuid();
    }

    @Override
    public String component8() {
        return getCuName();
    }

    @Override
    public LocalDateTime component9() {
        return getCtime();
    }

    @Override
    public Long component10() {
        return getMuid();
    }

    @Override
    public String component11() {
        return getMuName();
    }

    @Override
    public LocalDateTime component12() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFileId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getMessage();
    }

    @Override
    public Integer value6() {
        return getPercent();
    }

    @Override
    public Long value7() {
        return getCuid();
    }

    @Override
    public String value8() {
        return getCuName();
    }

    @Override
    public LocalDateTime value9() {
        return getCtime();
    }

    @Override
    public Long value10() {
        return getMuid();
    }

    @Override
    public String value11() {
        return getMuName();
    }

    @Override
    public LocalDateTime value12() {
        return getMtime();
    }

    @Override
    public FileProgressTempRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value2(String value) {
        setFileId(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value5(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value6(Integer value) {
        setPercent(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value7(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value8(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value9(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value10(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value11(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public FileProgressTempRecord value12(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public FileProgressTempRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, Long value7, String value8, LocalDateTime value9, Long value10, String value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileProgressTempRecord
     */
    public FileProgressTempRecord() {
        super(FileProgressTemp.FILE_PROGRESS_TEMP);
    }

    /**
     * Create a detached, initialised FileProgressTempRecord
     */
    public FileProgressTempRecord(Long id, String fileId, String name, String status, String message, Integer percent, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime) {
        super(FileProgressTemp.FILE_PROGRESS_TEMP);

        setId(id);
        setFileId(fileId);
        setName(name);
        setStatus(status);
        setMessage(message);
        setPercent(percent);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
    }
}
