/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.tables.FileUpload;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 分片上传会话表（低频，不分表）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileUploadRecord extends UpdatableRecordImpl<FileUploadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>file_upload.id</code>. 自增主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>file_upload.id</code>. 自增主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>file_upload.upload_id</code>. 上传会话ID，upload-开头
     */
    public void setUploadId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>file_upload.upload_id</code>. 上传会话ID，upload-开头
     */
    public String getUploadId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>file_upload.space_code</code>. 所属空间
     */
    public void setSpaceCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>file_upload.space_code</code>. 所属空间
     */
    public String getSpaceCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>file_upload.ak_code</code>. 发起方AK
     */
    public void setAkCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>file_upload.ak_code</code>. 发起方AK
     */
    public String getAkCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>file_upload.file_id</code>. 预生成的文件ID
     */
    public void setFileId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>file_upload.file_id</code>. 预生成的文件ID
     */
    public String getFileId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>file_upload.filename</code>. 文件名
     */
    public void setFilename(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>file_upload.filename</code>. 文件名
     */
    public String getFilename() {
        return (String) get(5);
    }

    /**
     * Setter for <code>file_upload.extension</code>. 扩展名
     */
    public void setExtension(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>file_upload.extension</code>. 扩展名
     */
    public String getExtension() {
        return (String) get(6);
    }

    /**
     * Setter for <code>file_upload.purpose</code>. 用途
     */
    public void setPurpose(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>file_upload.purpose</code>. 用途
     */
    public String getPurpose() {
        return (String) get(7);
    }

    /**
     * Setter for <code>file_upload.mime_type</code>. MIME类型
     */
    public void setMimeType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>file_upload.mime_type</code>. MIME类型
     */
    public String getMimeType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>file_upload.type</code>. 文件类型
     */
    public void setType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>file_upload.type</code>. 文件类型
     */
    public String getType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>file_upload.charset</code>. 字符集
     */
    public void setCharset(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>file_upload.charset</code>. 字符集
     */
    public String getCharset() {
        return (String) get(10);
    }

    /**
     * Setter for <code>file_upload.bucket</code>. 目标bucket
     */
    public void setBucket(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>file_upload.bucket</code>. 目标bucket
     */
    public String getBucket() {
        return (String) get(11);
    }

    /**
     * Setter for <code>file_upload.path</code>. 目标对象key
     */
    public void setPath(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>file_upload.path</code>. 目标对象key
     */
    public String getPath() {
        return (String) get(12);
    }

    /**
     * Setter for <code>file_upload.declared_bytes</code>. 声明的文件总大小
     */
    public void setDeclaredBytes(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>file_upload.declared_bytes</code>. 声明的文件总大小
     */
    public Long getDeclaredBytes() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>file_upload.storage_upload_id</code>. 底层multipart uploadId
     */
    public void setStorageUploadId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>file_upload.storage_upload_id</code>. 底层multipart uploadId
     */
    public String getStorageUploadId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>file_upload.ancestor_id</code>. 目标目录fileId
     */
    public void setAncestorId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>file_upload.ancestor_id</code>. 目标目录fileId
     */
    public String getAncestorId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>file_upload.metadata</code>. 业务元数据JSON
     */
    public void setMetadata(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>file_upload.metadata</code>. 业务元数据JSON
     */
    public String getMetadata() {
        return (String) get(16);
    }

    /**
     * Setter for <code>file_upload.description</code>. 描述
     */
    public void setDescription(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>file_upload.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(17);
    }

    /**
     * Setter for <code>file_upload.cities</code>. 城市JSON
     */
    public void setCities(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>file_upload.cities</code>. 城市JSON
     */
    public String getCities() {
        return (String) get(18);
    }

    /**
     * Setter for <code>file_upload.tags</code>. 标签JSON
     */
    public void setTags(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>file_upload.tags</code>. 标签JSON
     */
    public String getTags() {
        return (String) get(19);
    }

    /**
     * Setter for <code>file_upload.status</code>. PENDING/COMPLETING/COMPLETED/CANCELLED
     */
    public void setStatus(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>file_upload.status</code>. PENDING/COMPLETING/COMPLETED/CANCELLED
     */
    public String getStatus() {
        return (String) get(20);
    }

    /**
     * Setter for <code>file_upload.expires_at</code>. 会话过期时间
     */
    public void setExpiresAt(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>file_upload.expires_at</code>. 会话过期时间
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>file_upload.cuid</code>. 创建人ID
     */
    public void setCuid(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>file_upload.cuid</code>. 创建人ID
     */
    public Long getCuid() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>file_upload.cu_name</code>. 创建人姓名
     */
    public void setCuName(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>file_upload.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return (String) get(23);
    }

    /**
     * Setter for <code>file_upload.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime value) {
        set(24, value);
    }

    /**
     * Getter for <code>file_upload.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(24);
    }

    /**
     * Setter for <code>file_upload.mtime</code>. 更新时间
     */
    public void setMtime(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>file_upload.mtime</code>. 更新时间
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(25);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileUploadRecord
     */
    public FileUploadRecord() {
        super(FileUpload.FILE_UPLOAD);
    }

    /**
     * Create a detached, initialised FileUploadRecord
     */
    public FileUploadRecord(Long id, String uploadId, String spaceCode, String akCode, String fileId, String filename, String extension, String purpose, String mimeType, String type, String charset, String bucket, String path, Long declaredBytes, String storageUploadId, String ancestorId, String metadata, String description, String cities, String tags, String status, LocalDateTime expiresAt, Long cuid, String cuName, LocalDateTime ctime, LocalDateTime mtime) {
        super(FileUpload.FILE_UPLOAD);

        setId(id);
        setUploadId(uploadId);
        setSpaceCode(spaceCode);
        setAkCode(akCode);
        setFileId(fileId);
        setFilename(filename);
        setExtension(extension);
        setPurpose(purpose);
        setMimeType(mimeType);
        setType(type);
        setCharset(charset);
        setBucket(bucket);
        setPath(path);
        setDeclaredBytes(declaredBytes);
        setStorageUploadId(storageUploadId);
        setAncestorId(ancestorId);
        setMetadata(metadata);
        setDescription(description);
        setCities(cities);
        setTags(tags);
        setStatus(status);
        setExpiresAt(expiresAt);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMtime(mtime);
    }
}
