/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.FileSharding;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileShardingRecord extends UpdatableRecordImpl<FileShardingRecord> implements Operator, Record13<Long, String, String, LocalDateTime, String, Long, Long, LocalDateTime, String, Long, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>file_sharding.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>file_sharding.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>file_sharding.type</code>. 分片类型：temp-临时文件，system-系统文件
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>file_sharding.type</code>. 分片类型：temp-临时文件，system-系统文件
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>file_sharding.key</code>. 分表的标识，
     */
    public void setKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>file_sharding.key</code>. 分表的标识，
     */
    public String getKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>file_sharding.key_time</code>. 当前分片第一条数据的时间，用于索引分片
     */
    public void setKeyTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>file_sharding.key_time</code>. 当前分片第一条数据的时间，用于索引分片
     */
    public LocalDateTime getKeyTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>file_sharding.last_key</code>. 上一次分表的标识，用于分表创建并发控制
     */
    public void setLastKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>file_sharding.last_key</code>. 上一次分表的标识，用于分表创建并发控制
     */
    public String getLastKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>file_sharding.count</code>. 分表的记录数量
     */
    public void setCount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>file_sharding.count</code>. 分表的记录数量
     */
    public Long getCount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>file_sharding.max_count</code>. 分表的最大记录数
如果count&gt;max_count， 创建新表
     */
    public void setMaxCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>file_sharding.max_count</code>. 分表的最大记录数
如果count&gt;max_count， 创建新表
     */
    public Long getMaxCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>file_sharding.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>file_sharding.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>file_sharding.cu_name</code>.
     */
    public void setCuName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>file_sharding.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>file_sharding.cuid</code>.
     */
    public void setCuid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>file_sharding.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>file_sharding.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>file_sharding.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>file_sharding.mu_name</code>.
     */
    public void setMuName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>file_sharding.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>file_sharding.muid</code>.
     */
    public void setMuid(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>file_sharding.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, LocalDateTime, String, Long, Long, LocalDateTime, String, Long, LocalDateTime, String, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, LocalDateTime, String, Long, Long, LocalDateTime, String, Long, LocalDateTime, String, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FileSharding.FILE_SHARDING.ID;
    }

    @Override
    public Field<String> field2() {
        return FileSharding.FILE_SHARDING.TYPE;
    }

    @Override
    public Field<String> field3() {
        return FileSharding.FILE_SHARDING.KEY;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return FileSharding.FILE_SHARDING.KEY_TIME;
    }

    @Override
    public Field<String> field5() {
        return FileSharding.FILE_SHARDING.LAST_KEY;
    }

    @Override
    public Field<Long> field6() {
        return FileSharding.FILE_SHARDING.COUNT;
    }

    @Override
    public Field<Long> field7() {
        return FileSharding.FILE_SHARDING.MAX_COUNT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return FileSharding.FILE_SHARDING.CTIME;
    }

    @Override
    public Field<String> field9() {
        return FileSharding.FILE_SHARDING.CU_NAME;
    }

    @Override
    public Field<Long> field10() {
        return FileSharding.FILE_SHARDING.CUID;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return FileSharding.FILE_SHARDING.MTIME;
    }

    @Override
    public Field<String> field12() {
        return FileSharding.FILE_SHARDING.MU_NAME;
    }

    @Override
    public Field<Long> field13() {
        return FileSharding.FILE_SHARDING.MUID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public String component3() {
        return getKey();
    }

    @Override
    public LocalDateTime component4() {
        return getKeyTime();
    }

    @Override
    public String component5() {
        return getLastKey();
    }

    @Override
    public Long component6() {
        return getCount();
    }

    @Override
    public Long component7() {
        return getMaxCount();
    }

    @Override
    public LocalDateTime component8() {
        return getCtime();
    }

    @Override
    public String component9() {
        return getCuName();
    }

    @Override
    public Long component10() {
        return getCuid();
    }

    @Override
    public LocalDateTime component11() {
        return getMtime();
    }

    @Override
    public String component12() {
        return getMuName();
    }

    @Override
    public Long component13() {
        return getMuid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public String value3() {
        return getKey();
    }

    @Override
    public LocalDateTime value4() {
        return getKeyTime();
    }

    @Override
    public String value5() {
        return getLastKey();
    }

    @Override
    public Long value6() {
        return getCount();
    }

    @Override
    public Long value7() {
        return getMaxCount();
    }

    @Override
    public LocalDateTime value8() {
        return getCtime();
    }

    @Override
    public String value9() {
        return getCuName();
    }

    @Override
    public Long value10() {
        return getCuid();
    }

    @Override
    public LocalDateTime value11() {
        return getMtime();
    }

    @Override
    public String value12() {
        return getMuName();
    }

    @Override
    public Long value13() {
        return getMuid();
    }

    @Override
    public FileShardingRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FileShardingRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public FileShardingRecord value3(String value) {
        setKey(value);
        return this;
    }

    @Override
    public FileShardingRecord value4(LocalDateTime value) {
        setKeyTime(value);
        return this;
    }

    @Override
    public FileShardingRecord value5(String value) {
        setLastKey(value);
        return this;
    }

    @Override
    public FileShardingRecord value6(Long value) {
        setCount(value);
        return this;
    }

    @Override
    public FileShardingRecord value7(Long value) {
        setMaxCount(value);
        return this;
    }

    @Override
    public FileShardingRecord value8(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public FileShardingRecord value9(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public FileShardingRecord value10(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public FileShardingRecord value11(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public FileShardingRecord value12(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public FileShardingRecord value13(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public FileShardingRecord values(Long value1, String value2, String value3, LocalDateTime value4, String value5, Long value6, Long value7, LocalDateTime value8, String value9, Long value10, LocalDateTime value11, String value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileShardingRecord
     */
    public FileShardingRecord() {
        super(FileSharding.FILE_SHARDING);
    }

    /**
     * Create a detached, initialised FileShardingRecord
     */
    public FileShardingRecord(Long id, String type, String key, LocalDateTime keyTime, String lastKey, Long count, Long maxCount, LocalDateTime ctime, String cuName, Long cuid, LocalDateTime mtime, String muName, Long muid) {
        super(FileSharding.FILE_SHARDING);

        setId(id);
        setType(type);
        setKey(key);
        setKeyTime(keyTime);
        setLastKey(lastKey);
        setCount(count);
        setMaxCount(maxCount);
        setCtime(ctime);
        setCuName(cuName);
        setCuid(cuid);
        setMtime(mtime);
        setMuName(muName);
        setMuid(muid);
    }
}
