/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.File;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> implements Operator, Record18<Long, String, String, String, String, Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, String, Integer, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>file.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>file.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>file.file_id</code>. 文件ID
     */
    public void setFileId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>file.file_id</code>. 文件ID
     */
    public String getFileId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>file.filename</code>. 文件名
     */
    public void setFilename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>file.filename</code>. 文件名
     */
    public String getFilename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>file.bucket</code>. 存储的地方
     */
    public void setBucket(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>file.bucket</code>. 存储的地方
     */
    public String getBucket() {
        return (String) get(3);
    }

    /**
     * Setter for <code>file.path</code>. 文件路径
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>file.path</code>. 文件路径
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>file.bytes</code>. 文件大小；单位：字节
     */
    public void setBytes(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>file.bytes</code>. 文件大小；单位：字节
     */
    public Long getBytes() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>file.space_code</code>. 组织编码；对标OpenAI organization
     */
    public void setSpaceCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>file.space_code</code>. 组织编码；对标OpenAI organization
     */
    public String getSpaceCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>file.purpose</code>. 文件目的，参考OpenAI
     */
    public void setPurpose(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>file.purpose</code>. 文件目的，参考OpenAI
     */
    public String getPurpose() {
        return (String) get(7);
    }

    /**
     * Setter for <code>file.cuid</code>.
     */
    public void setCuid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>file.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>file.cu_name</code>.
     */
    public void setCuName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>file.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>file.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>file.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>file.muid</code>.
     */
    public void setMuid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>file.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>file.mu_name</code>.
     */
    public void setMuName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>file.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>file.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>file.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>file.meta_data</code>.
     */
    public void setMetaData(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>file.meta_data</code>.
     */
    public String getMetaData() {
        return (String) get(14);
    }

    /**
     * Setter for <code>file.status</code>. 文件是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>file.status</code>. 文件是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>file.ak_code</code>.
     */
    public void setAkCode(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>file.ak_code</code>.
     */
    public String getAkCode() {
        return (String) get(16);
    }

    /**
     * Setter for <code>file.broadcast_status</code>. 文件是否被广播成功，0表示广播失败，1表示广播成功
     */
    public void setBroadcastStatus(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>file.broadcast_status</code>. 文件是否被广播成功，0表示广播失败，1表示广播成功
     */
    public Long getBroadcastStatus() {
        return (Long) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, String, String, String, String, Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, String, Integer, String, Long> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, String, String, String, String, Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, String, Integer, String, Long> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return File.FILE.ID;
    }

    @Override
    public Field<String> field2() {
        return File.FILE.FILE_ID;
    }

    @Override
    public Field<String> field3() {
        return File.FILE.FILENAME;
    }

    @Override
    public Field<String> field4() {
        return File.FILE.BUCKET;
    }

    @Override
    public Field<String> field5() {
        return File.FILE.PATH;
    }

    @Override
    public Field<Long> field6() {
        return File.FILE.BYTES;
    }

    @Override
    public Field<String> field7() {
        return File.FILE.SPACE_CODE;
    }

    @Override
    public Field<String> field8() {
        return File.FILE.PURPOSE;
    }

    @Override
    public Field<Long> field9() {
        return File.FILE.CUID;
    }

    @Override
    public Field<String> field10() {
        return File.FILE.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return File.FILE.CTIME;
    }

    @Override
    public Field<Long> field12() {
        return File.FILE.MUID;
    }

    @Override
    public Field<String> field13() {
        return File.FILE.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return File.FILE.MTIME;
    }

    @Override
    public Field<String> field15() {
        return File.FILE.META_DATA;
    }

    @Override
    public Field<Integer> field16() {
        return File.FILE.STATUS;
    }

    @Override
    public Field<String> field17() {
        return File.FILE.AK_CODE;
    }

    @Override
    public Field<Long> field18() {
        return File.FILE.BROADCAST_STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFileId();
    }

    @Override
    public String component3() {
        return getFilename();
    }

    @Override
    public String component4() {
        return getBucket();
    }

    @Override
    public String component5() {
        return getPath();
    }

    @Override
    public Long component6() {
        return getBytes();
    }

    @Override
    public String component7() {
        return getSpaceCode();
    }

    @Override
    public String component8() {
        return getPurpose();
    }

    @Override
    public Long component9() {
        return getCuid();
    }

    @Override
    public String component10() {
        return getCuName();
    }

    @Override
    public LocalDateTime component11() {
        return getCtime();
    }

    @Override
    public Long component12() {
        return getMuid();
    }

    @Override
    public String component13() {
        return getMuName();
    }

    @Override
    public LocalDateTime component14() {
        return getMtime();
    }

    @Override
    public String component15() {
        return getMetaData();
    }

    @Override
    public Integer component16() {
        return getStatus();
    }

    @Override
    public String component17() {
        return getAkCode();
    }

    @Override
    public Long component18() {
        return getBroadcastStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFileId();
    }

    @Override
    public String value3() {
        return getFilename();
    }

    @Override
    public String value4() {
        return getBucket();
    }

    @Override
    public String value5() {
        return getPath();
    }

    @Override
    public Long value6() {
        return getBytes();
    }

    @Override
    public String value7() {
        return getSpaceCode();
    }

    @Override
    public String value8() {
        return getPurpose();
    }

    @Override
    public Long value9() {
        return getCuid();
    }

    @Override
    public String value10() {
        return getCuName();
    }

    @Override
    public LocalDateTime value11() {
        return getCtime();
    }

    @Override
    public Long value12() {
        return getMuid();
    }

    @Override
    public String value13() {
        return getMuName();
    }

    @Override
    public LocalDateTime value14() {
        return getMtime();
    }

    @Override
    public String value15() {
        return getMetaData();
    }

    @Override
    public Integer value16() {
        return getStatus();
    }

    @Override
    public String value17() {
        return getAkCode();
    }

    @Override
    public Long value18() {
        return getBroadcastStatus();
    }

    @Override
    public FileRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FileRecord value2(String value) {
        setFileId(value);
        return this;
    }

    @Override
    public FileRecord value3(String value) {
        setFilename(value);
        return this;
    }

    @Override
    public FileRecord value4(String value) {
        setBucket(value);
        return this;
    }

    @Override
    public FileRecord value5(String value) {
        setPath(value);
        return this;
    }

    @Override
    public FileRecord value6(Long value) {
        setBytes(value);
        return this;
    }

    @Override
    public FileRecord value7(String value) {
        setSpaceCode(value);
        return this;
    }

    @Override
    public FileRecord value8(String value) {
        setPurpose(value);
        return this;
    }

    @Override
    public FileRecord value9(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public FileRecord value10(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public FileRecord value11(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public FileRecord value12(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public FileRecord value13(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public FileRecord value14(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public FileRecord value15(String value) {
        setMetaData(value);
        return this;
    }

    @Override
    public FileRecord value16(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public FileRecord value17(String value) {
        setAkCode(value);
        return this;
    }

    @Override
    public FileRecord value18(Long value) {
        setBroadcastStatus(value);
        return this;
    }

    @Override
    public FileRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6, String value7, String value8, Long value9, String value10, LocalDateTime value11, Long value12, String value13, LocalDateTime value14, String value15, Integer value16, String value17, Long value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(File.FILE);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(Long id, String fileId, String filename, String bucket, String path, Long bytes, String spaceCode, String purpose, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime, String metaData, Integer status, String akCode, Long broadcastStatus) {
        super(File.FILE);

        setId(id);
        setFileId(fileId);
        setFilename(filename);
        setBucket(bucket);
        setPath(path);
        setBytes(bytes);
        setSpaceCode(spaceCode);
        setPurpose(purpose);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
        setMetaData(metaData);
        setStatus(status);
        setAkCode(akCode);
        setBroadcastStatus(broadcastStatus);
    }
}
