/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;

import java.time.LocalDateTime;

import org.jooq.impl.UpdatableRecordImpl;

import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.FileEntry;

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileEntryRecord extends UpdatableRecordImpl<FileEntryRecord> implements Operator {
    private static final long serialVersionUID = 1L;

    public FileEntryRecord() {
        super(FileEntry.FILE_ENTRY);
    }

    public void setId(Long value) { set(0, value); }
    public Long getId() { return (Long) get(0); }
    public void setEntryId(String value) { set(1, value); }
    public String getEntryId() { return (String) get(1); }
    public void setSpaceCode(String value) { set(2, value); }
    public String getSpaceCode() { return (String) get(2); }
    public void setParentEntryId(String value) { set(3, value); }
    public String getParentEntryId() { return (String) get(3); }
    public void setFileId(String value) { set(4, value); }
    public String getFileId() { return (String) get(4); }
    public void setFilename(String value) { set(5, value); }
    public String getFilename() { return (String) get(5); }
    public void setType(String value) { set(6, value); }
    public String getType() { return (String) get(6); }
    public void setStatus(Integer value) { set(7, value); }
    public Integer getStatus() { return (Integer) get(7); }
    public Integer getActiveFlag() { return (Integer) get(8); }
    public void setCuid(Long value) { set(9, value); }
    public Long getCuid() { return (Long) get(9); }
    public void setCuName(String value) { set(10, value); }
    public String getCuName() { return (String) get(10); }
    public void setCtime(LocalDateTime value) { set(11, value); }
    public LocalDateTime getCtime() { return (LocalDateTime) get(11); }
    public void setMuid(Long value) { set(12, value); }
    public Long getMuid() { return (Long) get(12); }
    public void setMuName(String value) { set(13, value); }
    public String getMuName() { return (String) get(13); }
    public void setMtime(LocalDateTime value) { set(14, value); }
    public LocalDateTime getMtime() { return (LocalDateTime) get(14); }
}
