/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.records;


import com.ke.bella.files.db.repo.Operator;
import com.ke.bella.files.db.tables.Tag;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 标签定义表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> implements Operator, Record10<Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tag.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tag.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tag.space_code</code>. 空间编码
     */
    public void setSpaceCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tag.space_code</code>. 空间编码
     */
    public String getSpaceCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tag.name</code>. 标签名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tag.name</code>. 标签名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tag.cuid</code>.
     */
    public void setCuid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>tag.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>tag.cu_name</code>.
     */
    public void setCuName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tag.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tag.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>tag.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>tag.muid</code>.
     */
    public void setMuid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>tag.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>tag.mu_name</code>.
     */
    public void setMuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tag.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tag.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>tag.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>tag.status</code>. 状态：0正常，-1删除
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>tag.status</code>. 状态：0正常，-1删除
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, Long, String, LocalDateTime, Long, String, LocalDateTime, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Tag.TAG.ID;
    }

    @Override
    public Field<String> field2() {
        return Tag.TAG.SPACE_CODE;
    }

    @Override
    public Field<String> field3() {
        return Tag.TAG.NAME;
    }

    @Override
    public Field<Long> field4() {
        return Tag.TAG.CUID;
    }

    @Override
    public Field<String> field5() {
        return Tag.TAG.CU_NAME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Tag.TAG.CTIME;
    }

    @Override
    public Field<Long> field7() {
        return Tag.TAG.MUID;
    }

    @Override
    public Field<String> field8() {
        return Tag.TAG.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Tag.TAG.MTIME;
    }

    @Override
    public Field<Integer> field10() {
        return Tag.TAG.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSpaceCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Long component4() {
        return getCuid();
    }

    @Override
    public String component5() {
        return getCuName();
    }

    @Override
    public LocalDateTime component6() {
        return getCtime();
    }

    @Override
    public Long component7() {
        return getMuid();
    }

    @Override
    public String component8() {
        return getMuName();
    }

    @Override
    public LocalDateTime component9() {
        return getMtime();
    }

    @Override
    public Integer component10() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSpaceCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Long value4() {
        return getCuid();
    }

    @Override
    public String value5() {
        return getCuName();
    }

    @Override
    public LocalDateTime value6() {
        return getCtime();
    }

    @Override
    public Long value7() {
        return getMuid();
    }

    @Override
    public String value8() {
        return getMuName();
    }

    @Override
    public LocalDateTime value9() {
        return getMtime();
    }

    @Override
    public Integer value10() {
        return getStatus();
    }

    @Override
    public TagRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TagRecord value2(String value) {
        setSpaceCode(value);
        return this;
    }

    @Override
    public TagRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public TagRecord value4(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public TagRecord value5(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public TagRecord value6(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public TagRecord value7(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public TagRecord value8(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public TagRecord value9(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public TagRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public TagRecord values(Long value1, String value2, String value3, Long value4, String value5, LocalDateTime value6, Long value7, String value8, LocalDateTime value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(Long id, String spaceCode, String name, Long cuid, String cuName, LocalDateTime ctime, Long muid, String muName, LocalDateTime mtime, Integer status) {
        super(Tag.TAG);

        setId(id);
        setSpaceCode(spaceCode);
        setName(name);
        setCuid(cuid);
        setCuName(cuName);
        setCtime(ctime);
        setMuid(muid);
        setMuName(muName);
        setMtime(mtime);
        setStatus(status);
    }
}
