/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import com.ke.bella.files.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 文档数据集表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetDocumentDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        datasetShardingKey;
    private String        datasetId;
    private String        fileId;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;
    private Integer       status;

    public DatasetDocumentDB() {}

    public DatasetDocumentDB(DatasetDocumentDB value) {
        this.id = value.id;
        this.datasetShardingKey = value.datasetShardingKey;
        this.datasetId = value.datasetId;
        this.fileId = value.fileId;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
        this.status = value.status;
    }

    public DatasetDocumentDB(
        Long          id,
        String        datasetShardingKey,
        String        datasetId,
        String        fileId,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime,
        Integer       status
    ) {
        this.id = id;
        this.datasetShardingKey = datasetShardingKey;
        this.datasetId = datasetId;
        this.fileId = fileId;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
        this.status = status;
    }

    /**
     * Getter for <code>dataset_document.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>dataset_document.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>dataset_document.dataset_sharding_key</code>. 数据集分片的key
     */
    public String getDatasetShardingKey() {
        return this.datasetShardingKey;
    }

    /**
     * Setter for <code>dataset_document.dataset_sharding_key</code>. 数据集分片的key
     */
    public void setDatasetShardingKey(String datasetShardingKey) {
        this.datasetShardingKey = datasetShardingKey;
    }

    /**
     * Getter for <code>dataset_document.dataset_id</code>. 数据集ID
     */
    public String getDatasetId() {
        return this.datasetId;
    }

    /**
     * Setter for <code>dataset_document.dataset_id</code>. 数据集ID
     */
    public void setDatasetId(String datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * Getter for <code>dataset_document.file_id</code>. 文件ID，作为document的主键
     */
    public String getFileId() {
        return this.fileId;
    }

    /**
     * Setter for <code>dataset_document.file_id</code>. 文件ID，作为document的主键
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * Getter for <code>dataset_document.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>dataset_document.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>dataset_document.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>dataset_document.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>dataset_document.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>dataset_document.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>dataset_document.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>dataset_document.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>dataset_document.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>dataset_document.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>dataset_document.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>dataset_document.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>dataset_document.status</code>. 文档是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>dataset_document.status</code>. 文档是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DatasetDocumentDB (");

        sb.append(id);
        sb.append(", ").append(datasetShardingKey);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(fileId);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
