/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import com.ke.bella.files.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 数据集问答对引用关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetQaReferenceDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        referenceId;
    private String        itemId;
    private String        datasetId;
    private String        fileId;
    private String        path;
    private String        snippet;
    private Integer       primary;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;
    private Integer       status;

    public DatasetQaReferenceDB() {}

    public DatasetQaReferenceDB(DatasetQaReferenceDB value) {
        this.id = value.id;
        this.referenceId = value.referenceId;
        this.itemId = value.itemId;
        this.datasetId = value.datasetId;
        this.fileId = value.fileId;
        this.path = value.path;
        this.snippet = value.snippet;
        this.primary = value.primary;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
        this.status = value.status;
    }

    public DatasetQaReferenceDB(
        Long          id,
        String        referenceId,
        String        itemId,
        String        datasetId,
        String        fileId,
        String        path,
        String        snippet,
        Integer       primary,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime,
        Integer       status
    ) {
        this.id = id;
        this.referenceId = referenceId;
        this.itemId = itemId;
        this.datasetId = datasetId;
        this.fileId = fileId;
        this.path = path;
        this.snippet = snippet;
        this.primary = primary;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
        this.status = status;
    }

    /**
     * Getter for <code>dataset_qa_reference.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>dataset_qa_reference.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>dataset_qa_reference.reference_id</code>. 引用ID；由item_id/file_id/path确定
     */
    public String getReferenceId() {
        return this.referenceId;
    }

    /**
     * Setter for <code>dataset_qa_reference.reference_id</code>. 引用ID；由item_id/file_id/path确定
     */
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * Getter for <code>dataset_qa_reference.item_id</code>. 问答对ID
     */
    public String getItemId() {
        return this.itemId;
    }

    /**
     * Setter for <code>dataset_qa_reference.item_id</code>. 问答对ID
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * Getter for <code>dataset_qa_reference.dataset_id</code>. 数据集ID
     */
    public String getDatasetId() {
        return this.datasetId;
    }

    /**
     * Setter for <code>dataset_qa_reference.dataset_id</code>. 数据集ID
     */
    public void setDatasetId(String datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * Getter for <code>dataset_qa_reference.file_id</code>. 文件ID
     */
    public String getFileId() {
        return this.fileId;
    }

    /**
     * Setter for <code>dataset_qa_reference.file_id</code>. 文件ID
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * Getter for <code>dataset_qa_reference.path</code>. 位置信息
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>dataset_qa_reference.path</code>. 位置信息
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for <code>dataset_qa_reference.snippet</code>. snippet for dataset qa reference
     */
    public String getSnippet() {
        return this.snippet;
    }

    /**
     * Setter for <code>dataset_qa_reference.snippet</code>. snippet for dataset qa reference
     */
    public void setSnippet(String snippet) {
        this.snippet = snippet;
    }

    /**
     * Getter for <code>dataset_qa_reference.primary</code>. 是否为关键知识，0表示普通知识，1表示关键知识
     */
    public Integer getPrimary() {
        return this.primary;
    }

    /**
     * Setter for <code>dataset_qa_reference.primary</code>. 是否为关键知识，0表示普通知识，1表示关键知识
     */
    public void setPrimary(Integer primary) {
        this.primary = primary;
    }

    /**
     * Getter for <code>dataset_qa_reference.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>dataset_qa_reference.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>dataset_qa_reference.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>dataset_qa_reference.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>dataset_qa_reference.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>dataset_qa_reference.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>dataset_qa_reference.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>dataset_qa_reference.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>dataset_qa_reference.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>dataset_qa_reference.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>dataset_qa_reference.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>dataset_qa_reference.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>dataset_qa_reference.status</code>. 引用是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>dataset_qa_reference.status</code>. 引用是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DatasetQaReferenceDB (");

        sb.append(id);
        sb.append(", ").append(referenceId);
        sb.append(", ").append(itemId);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(fileId);
        sb.append(", ").append(path);
        sb.append(", ").append(snippet);
        sb.append(", ").append(primary);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
