/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import com.ke.bella.files.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 数据集
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        spaceCode;
    private String        datasetId;
    private String        name;
    private String        type;
    private String        remark;
    private Long          count;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;
    private Integer       status;
    private LocalDateTime latestExportTime;
    private String        latestExportFileId;

    public DatasetDB() {}

    public DatasetDB(DatasetDB value) {
        this.id = value.id;
        this.spaceCode = value.spaceCode;
        this.datasetId = value.datasetId;
        this.name = value.name;
        this.type = value.type;
        this.remark = value.remark;
        this.count = value.count;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
        this.status = value.status;
        this.latestExportTime = value.latestExportTime;
        this.latestExportFileId = value.latestExportFileId;
    }

    public DatasetDB(
        Long          id,
        String        spaceCode,
        String        datasetId,
        String        name,
        String        type,
        String        remark,
        Long          count,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime,
        Integer       status,
        LocalDateTime latestExportTime,
        String        latestExportFileId
    ) {
        this.id = id;
        this.spaceCode = spaceCode;
        this.datasetId = datasetId;
        this.name = name;
        this.type = type;
        this.remark = remark;
        this.count = count;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
        this.status = status;
        this.latestExportTime = latestExportTime;
        this.latestExportFileId = latestExportFileId;
    }

    /**
     * Getter for <code>dataset.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>dataset.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>dataset.space_code</code>. 组织编码；对标OpenAI organization
     */
    public String getSpaceCode() {
        return this.spaceCode;
    }

    /**
     * Setter for <code>dataset.space_code</code>. 组织编码；对标OpenAI organization
     */
    public void setSpaceCode(String spaceCode) {
        this.spaceCode = spaceCode;
    }

    /**
     * Getter for <code>dataset.dataset_id</code>. 数据集ID
     */
    public String getDatasetId() {
        return this.datasetId;
    }

    /**
     * Setter for <code>dataset.dataset_id</code>. 数据集ID
     */
    public void setDatasetId(String datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * Getter for <code>dataset.name</code>. 数据集名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>dataset.name</code>. 数据集名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>dataset.type</code>. 类型；QA：QA类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>dataset.type</code>. 类型；QA：QA类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>dataset.remark</code>. 备注
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>dataset.remark</code>. 备注
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * Getter for <code>dataset.count</code>. 数量
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Setter for <code>dataset.count</code>. 数量
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * Getter for <code>dataset.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>dataset.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>dataset.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>dataset.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>dataset.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>dataset.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>dataset.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>dataset.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>dataset.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>dataset.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>dataset.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>dataset.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>dataset.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>dataset.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>dataset.latest_export_time</code>. 数据集最新导出时间
     */
    public LocalDateTime getLatestExportTime() {
        return this.latestExportTime;
    }

    /**
     * Setter for <code>dataset.latest_export_time</code>. 数据集最新导出时间
     */
    public void setLatestExportTime(LocalDateTime latestExportTime) {
        this.latestExportTime = latestExportTime;
    }

    /**
     * Getter for <code>dataset.latest_export_file_id</code>. 数据集最新导出文件ID
     */
    public String getLatestExportFileId() {
        return this.latestExportFileId;
    }

    /**
     * Setter for <code>dataset.latest_export_file_id</code>. 数据集最新导出文件ID
     */
    public void setLatestExportFileId(String latestExportFileId) {
        this.latestExportFileId = latestExportFileId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DatasetDB (");

        sb.append(id);
        sb.append(", ").append(spaceCode);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(remark);
        sb.append(", ").append(count);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);
        sb.append(", ").append(status);
        sb.append(", ").append(latestExportTime);
        sb.append(", ").append(latestExportFileId);

        sb.append(")");
        return sb.toString();
    }
}
