/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import com.ke.bella.files.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 问答数据集表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetQaDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        itemId;
    private String        datasetShardingKey;
    private String        datasetId;
    private String        question;
    private String        similarQ1;
    private String        similarQ2;
    private String        similarQ3;
    private String        answer;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;
    private Integer       status;

    public DatasetQaDB() {}

    public DatasetQaDB(DatasetQaDB value) {
        this.id = value.id;
        this.itemId = value.itemId;
        this.datasetShardingKey = value.datasetShardingKey;
        this.datasetId = value.datasetId;
        this.question = value.question;
        this.similarQ1 = value.similarQ1;
        this.similarQ2 = value.similarQ2;
        this.similarQ3 = value.similarQ3;
        this.answer = value.answer;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
        this.status = value.status;
    }

    public DatasetQaDB(
        Long          id,
        String        itemId,
        String        datasetShardingKey,
        String        datasetId,
        String        question,
        String        similarQ1,
        String        similarQ2,
        String        similarQ3,
        String        answer,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime,
        Integer       status
    ) {
        this.id = id;
        this.itemId = itemId;
        this.datasetShardingKey = datasetShardingKey;
        this.datasetId = datasetId;
        this.question = question;
        this.similarQ1 = similarQ1;
        this.similarQ2 = similarQ2;
        this.similarQ3 = similarQ3;
        this.answer = answer;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
        this.status = status;
    }

    /**
     * Getter for <code>dataset_qa.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>dataset_qa.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>dataset_qa.item_id</code>. QA的ID
     */
    public String getItemId() {
        return this.itemId;
    }

    /**
     * Setter for <code>dataset_qa.item_id</code>. QA的ID
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * Getter for <code>dataset_qa.dataset_sharding_key</code>. 数据集分片的key
     */
    public String getDatasetShardingKey() {
        return this.datasetShardingKey;
    }

    /**
     * Setter for <code>dataset_qa.dataset_sharding_key</code>. 数据集分片的key
     */
    public void setDatasetShardingKey(String datasetShardingKey) {
        this.datasetShardingKey = datasetShardingKey;
    }

    /**
     * Getter for <code>dataset_qa.dataset_id</code>. 数据集ID
     */
    public String getDatasetId() {
        return this.datasetId;
    }

    /**
     * Setter for <code>dataset_qa.dataset_id</code>. 数据集ID
     */
    public void setDatasetId(String datasetId) {
        this.datasetId = datasetId;
    }

    /**
     * Getter for <code>dataset_qa.question</code>. 问题
     */
    public String getQuestion() {
        return this.question;
    }

    /**
     * Setter for <code>dataset_qa.question</code>. 问题
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * Getter for <code>dataset_qa.similar_q1</code>. 相似问1
     */
    public String getSimilarQ1() {
        return this.similarQ1;
    }

    /**
     * Setter for <code>dataset_qa.similar_q1</code>. 相似问1
     */
    public void setSimilarQ1(String similarQ1) {
        this.similarQ1 = similarQ1;
    }

    /**
     * Getter for <code>dataset_qa.similar_q2</code>. 相似问2
     */
    public String getSimilarQ2() {
        return this.similarQ2;
    }

    /**
     * Setter for <code>dataset_qa.similar_q2</code>. 相似问2
     */
    public void setSimilarQ2(String similarQ2) {
        this.similarQ2 = similarQ2;
    }

    /**
     * Getter for <code>dataset_qa.similar_q3</code>. 相似问3
     */
    public String getSimilarQ3() {
        return this.similarQ3;
    }

    /**
     * Setter for <code>dataset_qa.similar_q3</code>. 相似问3
     */
    public void setSimilarQ3(String similarQ3) {
        this.similarQ3 = similarQ3;
    }

    /**
     * Getter for <code>dataset_qa.answer</code>. 答案
     */
    public String getAnswer() {
        return this.answer;
    }

    /**
     * Setter for <code>dataset_qa.answer</code>. 答案
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * Getter for <code>dataset_qa.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>dataset_qa.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>dataset_qa.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>dataset_qa.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>dataset_qa.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>dataset_qa.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>dataset_qa.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>dataset_qa.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>dataset_qa.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>dataset_qa.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>dataset_qa.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>dataset_qa.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>dataset_qa.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>dataset_qa.status</code>. 数据集是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DatasetQaDB (");

        sb.append(id);
        sb.append(", ").append(itemId);
        sb.append(", ").append(datasetShardingKey);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(question);
        sb.append(", ").append(similarQ1);
        sb.append(", ").append(similarQ2);
        sb.append(", ").append(similarQ3);
        sb.append(", ").append(answer);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
