/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;

import java.io.Serializable;
import java.time.LocalDateTime;

import com.ke.bella.files.db.repo.Operator;

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileEntryDB implements Serializable, Operator {
    private static final long serialVersionUID = 1L;
    private Long id;
    private String entryId;
    private String spaceCode;
    private String parentEntryId;
    private String fileId;
    private String filename;
    private String type;
    private Long cuid;
    private String cuName;
    private LocalDateTime ctime;
    private Long muid;
    private String muName;
    private LocalDateTime mtime;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getEntryId() { return entryId; }
    public void setEntryId(String entryId) { this.entryId = entryId; }
    public String getSpaceCode() { return spaceCode; }
    public void setSpaceCode(String spaceCode) { this.spaceCode = spaceCode; }
    public String getParentEntryId() { return parentEntryId; }
    public void setParentEntryId(String parentEntryId) { this.parentEntryId = parentEntryId; }
    public String getFileId() { return fileId; }
    public void setFileId(String fileId) { this.fileId = fileId; }
    public String getFilename() { return filename; }
    public void setFilename(String filename) { this.filename = filename; }
    public String getType() { return type; }
    public void setType(String type) { this.type = type; }
    public Long getCuid() { return cuid; }
    public void setCuid(Long cuid) { this.cuid = cuid; }
    public String getCuName() { return cuName; }
    public void setCuName(String cuName) { this.cuName = cuName; }
    public LocalDateTime getCtime() { return ctime; }
    public void setCtime(LocalDateTime ctime) { this.ctime = ctime; }
    public Long getMuid() { return muid; }
    public void setMuid(Long muid) { this.muid = muid; }
    public String getMuName() { return muName; }
    public void setMuName(String muName) { this.muName = muName; }
    public LocalDateTime getMtime() { return mtime; }
    public void setMtime(LocalDateTime mtime) { this.mtime = mtime; }
}
