/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import com.ke.bella.files.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 文件闭包表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileClosureDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        ancestorId;
    private String        descendantId;
    private String        spaceCode;
    private Long          depth;
    private Long          rootDepth;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;

    public FileClosureDB() {}

    public FileClosureDB(FileClosureDB value) {
        this.id = value.id;
        this.ancestorId = value.ancestorId;
        this.descendantId = value.descendantId;
        this.spaceCode = value.spaceCode;
        this.depth = value.depth;
        this.rootDepth = value.rootDepth;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
    }

    public FileClosureDB(
        Long          id,
        String        ancestorId,
        String        descendantId,
        String        spaceCode,
        Long          depth,
        Long          rootDepth,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.ancestorId = ancestorId;
        this.descendantId = descendantId;
        this.spaceCode = spaceCode;
        this.depth = depth;
        this.rootDepth = rootDepth;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>file_closure.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>file_closure.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>file_closure.ancestor_id</code>. 祖先 file_id
     */
    public String getAncestorId() {
        return this.ancestorId;
    }

    /**
     * Setter for <code>file_closure.ancestor_id</code>. 祖先 file_id
     */
    public void setAncestorId(String ancestorId) {
        this.ancestorId = ancestorId;
    }

    /**
     * Getter for <code>file_closure.descendant_id</code>. 后代 file_id
     */
    public String getDescendantId() {
        return this.descendantId;
    }

    /**
     * Setter for <code>file_closure.descendant_id</code>. 后代 file_id
     */
    public void setDescendantId(String descendantId) {
        this.descendantId = descendantId;
    }

    /**
     * Getter for <code>file_closure.space_code</code>. 组织编码；对标OpenAI organization
     */
    public String getSpaceCode() {
        return this.spaceCode;
    }

    /**
     * Setter for <code>file_closure.space_code</code>. 组织编码；对标OpenAI organization
     */
    public void setSpaceCode(String spaceCode) {
        this.spaceCode = spaceCode;
    }

    /**
     * Getter for <code>file_closure.depth</code>. 深度
     */
    public Long getDepth() {
        return this.depth;
    }

    /**
     * Setter for <code>file_closure.depth</code>. 深度
     */
    public void setDepth(Long depth) {
        this.depth = depth;
    }

    /**
     * Getter for <code>file_closure.root_depth</code>. 距离根目录的深度：1为根目录，2为第一级子文件...
     */
    public Long getRootDepth() {
        return this.rootDepth;
    }

    /**
     * Setter for <code>file_closure.root_depth</code>. 距离根目录的深度：1为根目录，2为第一级子文件...
     */
    public void setRootDepth(Long rootDepth) {
        this.rootDepth = rootDepth;
    }

    /**
     * Getter for <code>file_closure.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>file_closure.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>file_closure.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>file_closure.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>file_closure.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>file_closure.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>file_closure.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>file_closure.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>file_closure.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>file_closure.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>file_closure.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>file_closure.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FileClosureDB (");

        sb.append(id);
        sb.append(", ").append(ancestorId);
        sb.append(", ").append(descendantId);
        sb.append(", ").append(spaceCode);
        sb.append(", ").append(depth);
        sb.append(", ").append(rootDepth);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
