/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import com.ke.bella.files.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileMappingDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        fileId;
    private String        fileIdOld;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;

    public FileMappingDB() {}

    public FileMappingDB(FileMappingDB value) {
        this.id = value.id;
        this.fileId = value.fileId;
        this.fileIdOld = value.fileIdOld;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
    }

    public FileMappingDB(
        Long          id,
        String        fileId,
        String        fileIdOld,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.fileId = fileId;
        this.fileIdOld = fileIdOld;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>file_mapping.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>file_mapping.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>file_mapping.file_id</code>.
     */
    public String getFileId() {
        return this.fileId;
    }

    /**
     * Setter for <code>file_mapping.file_id</code>.
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * Getter for <code>file_mapping.file_id_old</code>. 老的file_id
     */
    public String getFileIdOld() {
        return this.fileIdOld;
    }

    /**
     * Setter for <code>file_mapping.file_id_old</code>. 老的file_id
     */
    public void setFileIdOld(String fileIdOld) {
        this.fileIdOld = fileIdOld;
    }

    /**
     * Getter for <code>file_mapping.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>file_mapping.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>file_mapping.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>file_mapping.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>file_mapping.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>file_mapping.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>file_mapping.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>file_mapping.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>file_mapping.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>file_mapping.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>file_mapping.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>file_mapping.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FileMappingDB (");

        sb.append(id);
        sb.append(", ").append(fileId);
        sb.append(", ").append(fileIdOld);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
