/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 分片上传会话表（低频，不分表）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileUploadDB implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        uploadId;
    private String        spaceCode;
    private String        akCode;
    private String        fileId;
    private String        filename;
    private String        extension;
    private String        purpose;
    private String        mimeType;
    private String        type;
    private String        charset;
    private String        bucket;
    private String        path;
    private Long          declaredBytes;
    private String        storageUploadId;
    private String        ancestorId;
    private String        metadata;
    private String        description;
    private String        cities;
    private String        tags;
    private String        status;
    private LocalDateTime expiresAt;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public FileUploadDB() {}

    public FileUploadDB(FileUploadDB value) {
        this.id = value.id;
        this.uploadId = value.uploadId;
        this.spaceCode = value.spaceCode;
        this.akCode = value.akCode;
        this.fileId = value.fileId;
        this.filename = value.filename;
        this.extension = value.extension;
        this.purpose = value.purpose;
        this.mimeType = value.mimeType;
        this.type = value.type;
        this.charset = value.charset;
        this.bucket = value.bucket;
        this.path = value.path;
        this.declaredBytes = value.declaredBytes;
        this.storageUploadId = value.storageUploadId;
        this.ancestorId = value.ancestorId;
        this.metadata = value.metadata;
        this.description = value.description;
        this.cities = value.cities;
        this.tags = value.tags;
        this.status = value.status;
        this.expiresAt = value.expiresAt;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public FileUploadDB(
        Long          id,
        String        uploadId,
        String        spaceCode,
        String        akCode,
        String        fileId,
        String        filename,
        String        extension,
        String        purpose,
        String        mimeType,
        String        type,
        String        charset,
        String        bucket,
        String        path,
        Long          declaredBytes,
        String        storageUploadId,
        String        ancestorId,
        String        metadata,
        String        description,
        String        cities,
        String        tags,
        String        status,
        LocalDateTime expiresAt,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.uploadId = uploadId;
        this.spaceCode = spaceCode;
        this.akCode = akCode;
        this.fileId = fileId;
        this.filename = filename;
        this.extension = extension;
        this.purpose = purpose;
        this.mimeType = mimeType;
        this.type = type;
        this.charset = charset;
        this.bucket = bucket;
        this.path = path;
        this.declaredBytes = declaredBytes;
        this.storageUploadId = storageUploadId;
        this.ancestorId = ancestorId;
        this.metadata = metadata;
        this.description = description;
        this.cities = cities;
        this.tags = tags;
        this.status = status;
        this.expiresAt = expiresAt;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>file_upload.id</code>. 自增主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>file_upload.id</code>. 自增主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>file_upload.upload_id</code>. 上传会话ID，upload-开头
     */
    public String getUploadId() {
        return this.uploadId;
    }

    /**
     * Setter for <code>file_upload.upload_id</code>. 上传会话ID，upload-开头
     */
    public void setUploadId(String uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * Getter for <code>file_upload.space_code</code>. 所属空间
     */
    public String getSpaceCode() {
        return this.spaceCode;
    }

    /**
     * Setter for <code>file_upload.space_code</code>. 所属空间
     */
    public void setSpaceCode(String spaceCode) {
        this.spaceCode = spaceCode;
    }

    /**
     * Getter for <code>file_upload.ak_code</code>. 发起方AK
     */
    public String getAkCode() {
        return this.akCode;
    }

    /**
     * Setter for <code>file_upload.ak_code</code>. 发起方AK
     */
    public void setAkCode(String akCode) {
        this.akCode = akCode;
    }

    /**
     * Getter for <code>file_upload.file_id</code>. 预生成的文件ID
     */
    public String getFileId() {
        return this.fileId;
    }

    /**
     * Setter for <code>file_upload.file_id</code>. 预生成的文件ID
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * Getter for <code>file_upload.filename</code>. 文件名
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>file_upload.filename</code>. 文件名
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * Getter for <code>file_upload.extension</code>. 扩展名
     */
    public String getExtension() {
        return this.extension;
    }

    /**
     * Setter for <code>file_upload.extension</code>. 扩展名
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for <code>file_upload.purpose</code>. 用途
     */
    public String getPurpose() {
        return this.purpose;
    }

    /**
     * Setter for <code>file_upload.purpose</code>. 用途
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    /**
     * Getter for <code>file_upload.mime_type</code>. MIME类型
     */
    public String getMimeType() {
        return this.mimeType;
    }

    /**
     * Setter for <code>file_upload.mime_type</code>. MIME类型
     */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     * Getter for <code>file_upload.type</code>. 文件类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>file_upload.type</code>. 文件类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>file_upload.charset</code>. 字符集
     */
    public String getCharset() {
        return this.charset;
    }

    /**
     * Setter for <code>file_upload.charset</code>. 字符集
     */
    public void setCharset(String charset) {
        this.charset = charset;
    }

    /**
     * Getter for <code>file_upload.bucket</code>. 目标bucket
     */
    public String getBucket() {
        return this.bucket;
    }

    /**
     * Setter for <code>file_upload.bucket</code>. 目标bucket
     */
    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    /**
     * Getter for <code>file_upload.path</code>. 目标对象key
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>file_upload.path</code>. 目标对象key
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for <code>file_upload.declared_bytes</code>. 声明的文件总大小
     */
    public Long getDeclaredBytes() {
        return this.declaredBytes;
    }

    /**
     * Setter for <code>file_upload.declared_bytes</code>. 声明的文件总大小
     */
    public void setDeclaredBytes(Long declaredBytes) {
        this.declaredBytes = declaredBytes;
    }

    /**
     * Getter for <code>file_upload.storage_upload_id</code>. 底层multipart uploadId
     */
    public String getStorageUploadId() {
        return this.storageUploadId;
    }

    /**
     * Setter for <code>file_upload.storage_upload_id</code>. 底层multipart uploadId
     */
    public void setStorageUploadId(String storageUploadId) {
        this.storageUploadId = storageUploadId;
    }

    /**
     * Getter for <code>file_upload.ancestor_id</code>. 目标目录fileId
     */
    public String getAncestorId() {
        return this.ancestorId;
    }

    /**
     * Setter for <code>file_upload.ancestor_id</code>. 目标目录fileId
     */
    public void setAncestorId(String ancestorId) {
        this.ancestorId = ancestorId;
    }

    /**
     * Getter for <code>file_upload.metadata</code>. 业务元数据JSON
     */
    public String getMetadata() {
        return this.metadata;
    }

    /**
     * Setter for <code>file_upload.metadata</code>. 业务元数据JSON
     */
    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }

    /**
     * Getter for <code>file_upload.description</code>. 描述
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>file_upload.description</code>. 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>file_upload.cities</code>. 城市JSON
     */
    public String getCities() {
        return this.cities;
    }

    /**
     * Setter for <code>file_upload.cities</code>. 城市JSON
     */
    public void setCities(String cities) {
        this.cities = cities;
    }

    /**
     * Getter for <code>file_upload.tags</code>. 标签JSON
     */
    public String getTags() {
        return this.tags;
    }

    /**
     * Setter for <code>file_upload.tags</code>. 标签JSON
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * Getter for <code>file_upload.status</code>. PENDING/COMPLETING/COMPLETED/CANCELLED
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>file_upload.status</code>. PENDING/COMPLETING/COMPLETED/CANCELLED
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>file_upload.expires_at</code>. 会话过期时间
     */
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Setter for <code>file_upload.expires_at</code>. 会话过期时间
     */
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * Getter for <code>file_upload.cuid</code>. 创建人ID
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>file_upload.cuid</code>. 创建人ID
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>file_upload.cu_name</code>. 创建人姓名
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>file_upload.cu_name</code>. 创建人姓名
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>file_upload.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>file_upload.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>file_upload.mtime</code>. 更新时间
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>file_upload.mtime</code>. 更新时间
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FileUploadDB (");

        sb.append(id);
        sb.append(", ").append(uploadId);
        sb.append(", ").append(spaceCode);
        sb.append(", ").append(akCode);
        sb.append(", ").append(fileId);
        sb.append(", ").append(filename);
        sb.append(", ").append(extension);
        sb.append(", ").append(purpose);
        sb.append(", ").append(mimeType);
        sb.append(", ").append(type);
        sb.append(", ").append(charset);
        sb.append(", ").append(bucket);
        sb.append(", ").append(path);
        sb.append(", ").append(declaredBytes);
        sb.append(", ").append(storageUploadId);
        sb.append(", ").append(ancestorId);
        sb.append(", ").append(metadata);
        sb.append(", ").append(description);
        sb.append(", ").append(cities);
        sb.append(", ").append(tags);
        sb.append(", ").append(status);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
