/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import com.ke.bella.files.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileProgressTempDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        fileId;
    private String        name;
    private String        status;
    private String        message;
    private Integer       percent;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;

    public FileProgressTempDB() {}

    public FileProgressTempDB(FileProgressTempDB value) {
        this.id = value.id;
        this.fileId = value.fileId;
        this.name = value.name;
        this.status = value.status;
        this.message = value.message;
        this.percent = value.percent;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
    }

    public FileProgressTempDB(
        Long          id,
        String        fileId,
        String        name,
        String        status,
        String        message,
        Integer       percent,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.fileId = fileId;
        this.name = name;
        this.status = status;
        this.message = message;
        this.percent = percent;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>file_progress_temp.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>file_progress_temp.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>file_progress_temp.file_id</code>. 文件id
     */
    public String getFileId() {
        return this.fileId;
    }

    /**
     * Setter for <code>file_progress_temp.file_id</code>. 文件id
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * Getter for <code>file_progress_temp.name</code>. 后处理名，一期由服务端枚举指定
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>file_progress_temp.name</code>. 后处理名，一期由服务端枚举指定
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>file_progress_temp.status</code>. 自定义状态，file api维护
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>file_progress_temp.status</code>. 自定义状态，file api维护
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>file_progress_temp.message</code>. 自定义信息，后处理维护
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Setter for <code>file_progress_temp.message</code>. 自定义信息，后处理维护
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for <code>file_progress_temp.percent</code>. 进度,单位百分比,0~100，后处理维护
     */
    public Integer getPercent() {
        return this.percent;
    }

    /**
     * Setter for <code>file_progress_temp.percent</code>. 进度,单位百分比,0~100，后处理维护
     */
    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    /**
     * Getter for <code>file_progress_temp.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>file_progress_temp.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>file_progress_temp.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>file_progress_temp.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>file_progress_temp.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>file_progress_temp.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>file_progress_temp.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>file_progress_temp.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>file_progress_temp.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>file_progress_temp.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>file_progress_temp.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>file_progress_temp.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FileProgressTempDB (");

        sb.append(id);
        sb.append(", ").append(fileId);
        sb.append(", ").append(name);
        sb.append(", ").append(status);
        sb.append(", ").append(message);
        sb.append(", ").append(percent);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
