/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;

import java.io.Serializable;
import java.time.LocalDateTime;
import com.ke.bella.files.db.repo.Operator;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        fileId;
    private Long          version;
    private String        filename;
    private Integer       isDir;
    private String        extension;
    private String        mimeType;
    private String        type;
    private String        bucket;
    private String        path;
    private Long          bytes;
    private String        spaceCode;
    private String        purpose;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;
    private String        metaData;
    private Integer       status;
    private String        akCode;
    private Long          broadcastStatus;
    private String        domTreeFileId;
    private String        pdfFileId;
    private String description;
    private String cities;
    private String tags;

    public FileDB() {}

    public FileDB(FileDB value) {
        this.id = value.id;
        this.fileId = value.fileId;
        this.version = value.version;
        this.filename = value.filename;
        this.isDir = value.isDir;
        this.extension = value.extension;
        this.mimeType = value.mimeType;
        this.type = value.type;
        this.bucket = value.bucket;
        this.path = value.path;
        this.bytes = value.bytes;
        this.spaceCode = value.spaceCode;
        this.purpose = value.purpose;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
        this.metaData = value.metaData;
        this.status = value.status;
        this.akCode = value.akCode;
        this.broadcastStatus = value.broadcastStatus;
        this.domTreeFileId = value.domTreeFileId;
        this.pdfFileId = value.pdfFileId;
        this.description = value.description;
        this.cities = value.cities;
        this.tags = value.tags;
    }

    public FileDB(
        Long          id,
        String        fileId,
        Long          version,
        String        filename,
        Integer       isDir,
        String        extension,
        String        mimeType,
        String        type,
        String        bucket,
        String        path,
        Long          bytes,
        String        spaceCode,
        String        purpose,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime,
        String        metaData,
        Integer       status,
        String        akCode,
        Long          broadcastStatus,
        String        domTreeFileId,
        String pdfFileId,
        String description,
        String cities,
        String tags
    ) {
        this.id = id;
        this.fileId = fileId;
        this.version = version;
        this.filename = filename;
        this.isDir = isDir;
        this.extension = extension;
        this.mimeType = mimeType;
        this.type = type;
        this.bucket = bucket;
        this.path = path;
        this.bytes = bytes;
        this.spaceCode = spaceCode;
        this.purpose = purpose;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
        this.metaData = metaData;
        this.status = status;
        this.akCode = akCode;
        this.broadcastStatus = broadcastStatus;
        this.domTreeFileId = domTreeFileId;
        this.pdfFileId = pdfFileId;
        this.description = description;
        this.cities = cities;
        this.tags = tags;
    }

    /**
     * Getter for <code>file.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>file.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>file.file_id</code>. 文件ID
     */
    public String getFileId() {
        return this.fileId;
    }

    /**
     * Setter for <code>file.file_id</code>. 文件ID
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * Getter for <code>file.version</code>. 文件版本号, 每次变更+1
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>file.version</code>. 文件版本号, 每次变更+1
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for <code>file.filename</code>. 文件名
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>file.filename</code>. 文件名
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * Getter for <code>file.is_dir</code>. 是否为目录：1为目录，0为文件
     */
    public Integer getIsDir() {
        return this.isDir;
    }

    /**
     * Setter for <code>file.is_dir</code>. 是否为目录：1为目录，0为文件
     */
    public void setIsDir(Integer isDir) {
        this.isDir = isDir;
    }

    /**
     * Getter for <code>file.extension</code>. extension
     */
    public String getExtension() {
        return this.extension;
    }

    /**
     * Setter for <code>file.extension</code>. extension
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for <code>file.mime_type</code>. mime type
     */
    public String getMimeType() {
        return this.mimeType;
    }

    /**
     * Setter for <code>file.mime_type</code>. mime type
     */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     * Getter for <code>file.type</code>. subtype of mime type, also known as file type
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>file.type</code>. subtype of mime type, also known as file type
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>file.bucket</code>. 存储的地方
     */
    public String getBucket() {
        return this.bucket;
    }

    /**
     * Setter for <code>file.bucket</code>. 存储的地方
     */
    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    /**
     * Getter for <code>file.path</code>. 文件路径
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>file.path</code>. 文件路径
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for <code>file.bytes</code>. 文件大小；单位：字节
     */
    public Long getBytes() {
        return this.bytes;
    }

    /**
     * Setter for <code>file.bytes</code>. 文件大小；单位：字节
     */
    public void setBytes(Long bytes) {
        this.bytes = bytes;
    }

    /**
     * Getter for <code>file.space_code</code>. 组织编码；对标OpenAI organization
     */
    public String getSpaceCode() {
        return this.spaceCode;
    }

    /**
     * Setter for <code>file.space_code</code>. 组织编码；对标OpenAI organization
     */
    public void setSpaceCode(String spaceCode) {
        this.spaceCode = spaceCode;
    }

    /**
     * Getter for <code>file.purpose</code>. 文件目的，参考OpenAI
     */
    public String getPurpose() {
        return this.purpose;
    }

    /**
     * Setter for <code>file.purpose</code>. 文件目的，参考OpenAI
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    /**
     * Getter for <code>file.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>file.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>file.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>file.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>file.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>file.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>file.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>file.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>file.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>file.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>file.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>file.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>file.meta_data</code>.
     */
    public String getMetaData() {
        return this.metaData;
    }

    /**
     * Setter for <code>file.meta_data</code>.
     */
    public void setMetaData(String metaData) {
        this.metaData = metaData;
    }

    /**
     * Getter for <code>file.status</code>. 文件是否被删除，0表示未删除，-1表示已删除
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>file.status</code>. 文件是否被删除，0表示未删除，-1表示已删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>file.ak_code</code>.
     */
    public String getAkCode() {
        return this.akCode;
    }

    /**
     * Setter for <code>file.ak_code</code>.
     */
    public void setAkCode(String akCode) {
        this.akCode = akCode;
    }

    /**
     * Getter for <code>file.broadcast_status</code>. 文件是否被广播成功，0表示广播失败，1表示广播成功
     */
    public Long getBroadcastStatus() {
        return this.broadcastStatus;
    }

    /**
     * Setter for <code>file.broadcast_status</code>. 文件是否被广播成功，0表示广播失败，1表示广播成功
     */
    public void setBroadcastStatus(Long broadcastStatus) {
        this.broadcastStatus = broadcastStatus;
    }

    /**
     * Getter for <code>file.dom_tree_file_id</code>. DOM tree的文件ID
     */
    public String getDomTreeFileId() {
        return this.domTreeFileId;
    }

    /**
     * Setter for <code>file.dom_tree_file_id</code>. DOM tree的文件ID
     */
    public void setDomTreeFileId(String domTreeFileId) {
        this.domTreeFileId = domTreeFileId;
    }

    /**
     * Getter for <code>file.pdf_file_id</code>. PDF的文件ID
     */
    public String getPdfFileId() {
        return this.pdfFileId;
    }

    /**
     * Setter for <code>file.pdf_file_id</code>. PDF的文件ID
     */
    public void setPdfFileId(String pdfFileId) {
        this.pdfFileId = pdfFileId;
    }

    /**
     * Getter for <code>file.description</code>. 描述
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>file.description</code>. 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>file.cities</code>. 作用城市,示例["北京","上海"]
     */
    public String getCities() {
        return this.cities;
    }

    /**
     * Setter for <code>file.cities</code>. 作用城市,示例["北京","上海"]
     */
    public void setCities(String cities) {
        this.cities = cities;
    }

    /**
     * Getter for <code>file.tags</code>. 标签,示例["tag1","tag2"]
     */
    public String getTags() {
        return this.tags;
    }

    /**
     * Setter for <code>file.tags</code>. 标签,示例["tag1","tag2"]
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FileDB (");

        sb.append(id);
        sb.append(", ").append(fileId);
        sb.append(", ").append(version);
        sb.append(", ").append(filename);
        sb.append(", ").append(isDir);
        sb.append(", ").append(extension);
        sb.append(", ").append(mimeType);
        sb.append(", ").append(type);
        sb.append(", ").append(bucket);
        sb.append(", ").append(path);
        sb.append(", ").append(bytes);
        sb.append(", ").append(spaceCode);
        sb.append(", ").append(purpose);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);
        sb.append(", ").append(metaData);
        sb.append(", ").append(status);
        sb.append(", ").append(akCode);
        sb.append(", ").append(broadcastStatus);
        sb.append(", ").append(domTreeFileId);
        sb.append(", ").append(pdfFileId);
        sb.append(", ").append(description);
        sb.append(", ").append(cities);
        sb.append(", ").append(tags);

        sb.append(")");
        return sb.toString();
    }
}
