/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.files.db.tables.pojos;


import com.ke.bella.files.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 标签定义表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        spaceCode;
    private String        name;
    private Long          cuid;
    private String        cuName;
    private LocalDateTime ctime;
    private Long          muid;
    private String        muName;
    private LocalDateTime mtime;
    private Integer       status;

    public TagDB() {}

    public TagDB(TagDB value) {
        this.id = value.id;
        this.spaceCode = value.spaceCode;
        this.name = value.name;
        this.cuid = value.cuid;
        this.cuName = value.cuName;
        this.ctime = value.ctime;
        this.muid = value.muid;
        this.muName = value.muName;
        this.mtime = value.mtime;
        this.status = value.status;
    }

    public TagDB(
        Long          id,
        String        spaceCode,
        String        name,
        Long          cuid,
        String        cuName,
        LocalDateTime ctime,
        Long          muid,
        String        muName,
        LocalDateTime mtime,
        Integer       status
    ) {
        this.id = id;
        this.spaceCode = spaceCode;
        this.name = name;
        this.cuid = cuid;
        this.cuName = cuName;
        this.ctime = ctime;
        this.muid = muid;
        this.muName = muName;
        this.mtime = mtime;
        this.status = status;
    }

    /**
     * Getter for <code>tag.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>tag.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>tag.space_code</code>. 空间编码
     */
    public String getSpaceCode() {
        return this.spaceCode;
    }

    /**
     * Setter for <code>tag.space_code</code>. 空间编码
     */
    public void setSpaceCode(String spaceCode) {
        this.spaceCode = spaceCode;
    }

    /**
     * Getter for <code>tag.name</code>. 标签名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>tag.name</code>. 标签名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>tag.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>tag.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>tag.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>tag.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>tag.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>tag.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>tag.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>tag.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>tag.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>tag.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>tag.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>tag.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    /**
     * Getter for <code>tag.status</code>. 状态：0正常，-1删除
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>tag.status</code>. 状态：0正常，-1删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TagDB (");

        sb.append(id);
        sb.append(", ").append(spaceCode);
        sb.append(", ").append(name);
        sb.append(", ").append(cuid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(muid);
        sb.append(", ").append(muName);
        sb.append(", ").append(mtime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
