CREATE TABLE `file_upload` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `upload_id` varchar(64) NOT NULL COMMENT '上传会话ID，upload-开头',
    `space_code` varchar(128) NOT NULL DEFAULT '' COMMENT '所属空间',
    `ak_code` varchar(128) NOT NULL DEFAULT '' COMMENT '发起方AK',
    `file_id` varchar(256) NOT NULL DEFAULT '' COMMENT '预生成的文件ID',
    `filename` varchar(512) NOT NULL COMMENT '文件名',
    `extension` varchar(512) NOT NULL DEFAULT '' COMMENT '扩展名',
    `purpose` varchar(64) NOT NULL COMMENT '用途',
    `mime_type` varchar(512) NOT NULL DEFAULT '' COMMENT 'MIME类型',
    `type` varchar(512) NOT NULL DEFAULT '' COMMENT '文件类型',
    `charset` varchar(32) NOT NULL DEFAULT '' COMMENT '字符集',
    `bucket` varchar(256) NOT NULL COMMENT '目标bucket',
    `path` varchar(512) NOT NULL COMMENT '目标对象key',
    `declared_bytes` bigint NOT NULL COMMENT '声明的文件总大小',
    `storage_upload_id` varchar(256) NOT NULL COMMENT '底层multipart uploadId',
    `ancestor_id` varchar(64) NOT NULL DEFAULT '' COMMENT '目标目录fileId',
    `metadata` text COMMENT '业务元数据JSON',
    `description` varchar(256) NOT NULL DEFAULT '' COMMENT '描述',
    `cities` varchar(512) NOT NULL DEFAULT '' COMMENT '城市JSON',
    `tags` varchar(512) NOT NULL DEFAULT '' COMMENT '标签JSON',
    `status` varchar(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/COMPLETING/COMPLETED/CANCELLED',
    `expires_at` datetime NOT NULL COMMENT '会话过期时间',
    `cuid` bigint NOT NULL DEFAULT 0 COMMENT '创建人ID',
    `cu_name` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人姓名',
    `ctime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `mtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_upload_id` (`upload_id`),
    KEY `idx_space_status` (`space_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分片上传会话表（低频，不分表）';
